### ISSUE TITLE
tag V1.6.2 src\main\java missing

### ISSUE THREAD

**Issue by sctianwei** [moqui/moqui-framework#102]
There is no src\main\java in tag V1.6.2

**Comment by jonesde** [comment]
That is correct, there is no src/main/java directory in version 1.6.2. That was not added until after the 1.6.2 release, moving toward the 2.0.0 release.

What is the issue?

**Comment by jonesde** [comment]
I don't see a bug report or feature request of any sort here, so closing this issue.
