### ISSUE TITLE
Is toString() method in EmailECARule.groovy appending extra \n?

### ISSUE THREAD

**Issue by ronankeane** [moqui/moqui-framework#105]
I'm trying to trace back the toString() method to see if there is an Override somewhere. Or not?

The outcome of the method is that single line breaks are turned into double line breaks in parsing of contentText.

E.g. Emails are formatted as follows: (EDIT: GITHUB IS ACTUALLY REMOVING THE DOUBLE LINEBREAKS I INSERTED BELOW... SO FOR EACH NEW LINE, ADD AN EXTRA ONE...)

Dear John Doe 
 
  
 
FYI 
 
  
 
https://www.xxxxxxxxxxx.ie/help-resources/information-videos/how-to-submit....
 
  
 
  
 
Regards 
 
  
 
John 

John Smith
 
Head of Company
 
Acme 
 
Address 1
 
Address 2
 
T: xxx
 
E: xxx
 
W: xxxxxxxx

**Comment by jonesde** [comment]
To look into this issue I need a way to reproduce it. There could be something funny in the text encoding. All Moqui is doing with body content is either calling toString() for CharSequence objects coming from javax.mail to populate contentText for a body part, or calling IOUtils.toByteArray() for InputStream objects to get the bytes and populate contentBytes. That is probably the most suspect, getting the plain bytes and storing them as various things can happen with different character sets.

Which service are you using to persist the content of the email body parts, and what is it doing with contentText and contentBytes?

**Comment by ronankeane** [comment]
I am just using <set field="body" from="bodyPartList ? bodyPartList[0].contentText : null" /> from the save#EcaEmailMessage service. 

Is that what you mean?

I will double check now, but I am certain polling any mail box with the default services in Moqui, writing to the basic.EmailMessage entity, the body is parsed like this.

**Comment by ronankeane** [comment]
Confirmed as above.

**Comment by ronankeane** [comment]
Closing this. This behaviour actually seems to be coming from somewhere else. I double checked the entity entries through the tools application and the entries there seem different to how it is being rendered in my text-area field.
