### ISSUE TITLE
Loading "data types: ALL" when using MoquiProductionConf.xml 

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#106]
When using the MoquiProductionConf.xml, it is suppose only load seed data, but it loads all types. 

![image](https://cloud.githubusercontent.com/assets/4743845/18386750/7f33341c-76cb-11e6-9588-95115de2da13.png)

![image](https://cloud.githubusercontent.com/assets/4743845/18386758/873bf522-76cb-11e6-94fd-aa1bfa650512.png)

**Comment by jonesde** [comment]
The current MoquiDefaultConf.xml file specifies "seed,seed-initial,install" for empty-db-load, and the MoquiProductionConf.xml file has been simplified to mostly use settings from MoquiDefaultConf.xml (which is meant to be a basic production configuration, i.e. production by default).

What does your merged configuration file look like? Moqui now saves this in runtime/log/MoquiActualConf.xml.

**Comment by jonesde** [comment]
BTW, I tested this after doing a 'gradle cleanAll build' and running 'java -Dmoqui.conf=conf/MoquiProductionCont.xml -jar moqui-2.0.0.war' and it worked fine, i.e. types to load were '[seed, install, seed-initial]'.

**Comment by shendepu** [comment]
I just clean clone the framework, and run with

    gradle cleanAll build loadProduction runProduction

which use MoquiProductionConf.xml. and it still loads datatype all which includes demo data. 

The log still shows

    o.moqui.i.e.EntityDataLoaderImpl Loading data types: ALL

while actual data types in merged MoquiActualConf.xml

    empty-db-load="seed,seed-initial,install" 

But when run gradle loadProduction, the test account john.doe exists which means demo type data is loaded.

**Comment by shendepu** [comment]
If I run 

    gradle cleanAll build && java -Dmoqui.conf=conf/MoquiProductionConf.xml -jar moqui-2.0.0.war

Then it is right. 

if run 

    java -Dmoqui.conf=conf/MoquiProductionConf.xml -jar moqui-2.0.0.war -load

then it loads all data types. 

I know `-load` can append with `-types` parameters to specify which type to be loaded. Would it be better to load empty-db-load types of conf file if no `-types` parameter appended for `-load`?

**Comment by jonesde** [comment]
An explicit load is very different from the automatic load that is controlled by the @empty-db-load attribute. An explicit load ignores that attribute, just as it always has.

When you explicitly run the load command you must specify -types on the command line if you don't want it to load all types. This has been that way since the beginning of moqui. For a summary of supported command line arguments run 'java -jar moqui.war -?'.
