### ISSUE TITLE
output Map of org.moqui.impl.EmailServices.send#EmailTemplate is not correct

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#107]
the service interface org.moqui.EmailServices.send#EmailTemplate has following out-parameters

```
<out-parameters>
            <parameter name="messageId"><description>From the Message-ID email header field.</description></parameter>
            <parameter name="emailMessageId"><description>If createEmailMessage=true the ID of the EmailMessage record.</description></parameter>
        </out-parameters>
```
In service implementation (org.moqui.impl.EmailServices.send#EmailTemplate), script "sendEmailTemplate.groovy" has last statement as following if email is sent sucessfully:

```
ec.service.sync().name("update", "moqui.basic.email.EmailMessage").parameters(uemParms).disableAuthz().call()
```

This will cause service's output Map is the result of this Entity Auto service, which is [oldStatusId, statusChanged].

We must put one more line after this statement to return null, so that correct output Map will be built

**Comment by jonesde** [comment]
Thank you, this is fixed in commit #272e499.
