### ISSUE TITLE
xml-form-2.0.xsd - error in form-list.multi attribute description

### ISSUE THREAD

**Issue by igorgallingani** [moqui/moqui-framework#109]
Default to false:

<xs:attribute name="multi" default="false" type="boolean">
                <xs:annotation><xs:documentation>Make the form a multi-submit form where all rows on a page are
                    submitted together in a single request with a "_${rowNumber}" suffix on each field. Also passes a
                    _isMulti=true parameter so the Service Facade knows to run the service (a single service-call in a
                    transition) for each row. Defaults to true, so set to false to disable this behavior and have a
                    separate form (submitted separately) for each row.</xs:documentation></xs:annotation>
            </xs:attribute>

**Comment by jonesde** [comment]
Thank you, the annotation is corrected in commit #a6f7e20.
