### ISSUE TITLE
auto-fields-entity enhancement

### ISSUE THREAD

**Issue by igorgallingani** [moqui/moqui-framework#111]
Hi David, what do you think about changing the auto-fields-entity.include attribute (in  addEntityFields method) so that it can contain the list of fields to be generated?
The change may be useful in cases like AutoScreens.xml (parametric screen).

**Comment by jonesde** [comment]
I've thought about doing something like that, but instead of changing how the @include attribute works I'd prefer to use the same pattern as in the view-entity.alias-all element, ie an exclude sub-element.

Thoughts? Does that work for the use you had in mind?

**Comment by igorgallingani** [comment]
OK for me.
I plan to introduce artifacts in a simplified format (more plain english) for entities, screens, forms, actions . For the moment I'm trying a combination of markdown - groovy . I'll keep you updated.

**Comment by jonesde** [comment]
The exclude element is now supported for form auto-fields-service and auto-fields-entity in commit #d4024c4.
