### ISSUE TITLE
The entity auto service does not generate primary ID automatically

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/moqui-framework#112]
1. Select servcie create#moqui.example.Example in Tools->Service->Service Run
2. Enter example name only
3.  Run the service
4. I get a new record in exmple table in db but wihtout primary ID. I dont think it is expected.

I alse tried some other entity auto services and got same result. 

I use postgres 9.1

**Comment by chunlinyao** [comment]
The database will not store record without primary ID. I think the pk is a empty string `""`.

**Comment by zhangwei1979** [comment]
@chunlinyao ah, yes. The primary key is a empty string.

**Comment by jonesde** [comment]
This should be fixed in commit #dc92e06, please verify.

**Comment by zhangwei1979** [comment]
It works now
