### ISSUE TITLE
Should UserFacade.loginUserKey throw AuthenticationRequiredException if loginKey is invalid or expired?

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#116]
When using api_key to access REST API, the api return 500 error code if api_key is invalid. From client perspective, it seems 401 is more reasonable if api_key is not invalid or expired. 

Before WebFacadeImpl.handleSErviceRestCall, UserFacade calls loginUserKey. It only returns false, but not throw AuthenticationRequiredException if loginKey is invalid or expired. 

Using loginKey to do internal login is just like using username and password to login, then invalid loginKey is just like invalid username password. Although standards does not explicitly say which response code should be if login fails, I found some reference that 401 is usually return if authentication credential is missing or incorrect. (twitter use 401 https://dev.twitter.com/overview/api/response-codes).

I created a pull request https://github.com/moqui/moqui-framework/pull/115 on this. It uses a new request attribute "moqui.request.loginKeyValid" since AuthenticationRequiredException can be used because a json response is desired than error page.

**Comment by jonesde** [comment]
I did something a bit different from your pull request, but this is implemented in commit #935a97f.
