### ISSUE TITLE
Cannot compile code - ScheduledJobRunner.groovy

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#118]
A strange issue occured. There is a compilation warning:

![image](https://cloud.githubusercontent.com/assets/14863763/18604330/b52f7f2a-7c7b-11e6-90e1-c6f904740158.png)

![image](https://cloud.githubusercontent.com/assets/14863763/18604384/42d225e4-7c7c-11e6-8547-41933bf12366.png)

When I open the declaration of isBefore, it displays this info:
![image](https://cloud.githubusercontent.com/assets/14863763/18604355/ddfb2d8c-7c7b-11e6-98be-8f869585d0b6.png)

**Comment by jonesde** [comment]
Are you using Java 8 in your IDE? The current code uses the java.time classes from Java 8. In the latest code the Joda Time classes are not even imported, and the Joda Time jars are not added in the framework/build.gradle file. I'd recommend updating your IDE settings as well, in IntelliJ IDEA you can refresh from the gradle files.

**Comment by mrovnanik** [comment]
Yes, I suppose I am using Java 8:

![image](https://cloud.githubusercontent.com/assets/14863763/18604541/27ca8d7a-7c7e-11e6-8a9c-282f0c9b2923.png)

**Comment by mrovnanik** [comment]
Shall I download new JDK? I can see there is 8u102 available.

**Comment by mrovnanik** [comment]
OK, got this one covered. Thanks David, once again.

**Comment by jonesde** [comment]
No problem, this is the downside to changing so much right now in the framework... planning to get back to the normal much more stable libraries, API, etc after the 2.0.0 release.
