### ISSUE TITLE
view list cache not cleared on create of record not included when none of the field in condition

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#119]
This may not a bug, just not supported now. It is difficult to implement it. The following test will reproduce it.

    def "auto cache clear for view list on create of record not included may not work"() {
        // this is similar to what happens with authz checking with changes after startup
        when:
        EntityList beforeList = ec.entity.find("moqui.security.ArtifactAuthzCheckView")
                .condition("userGroupId", "ALL_USERS").useCache(true).list()
        EntityValue ev = ec.entity.makeValue("moqui.security.ArtifactGroupMember")
                .setAll([artifactGroupId:"SCREEN_TREE", artifactName: "TEST",
                         artifactTypeEnumId:"AT_XML_SCREEN"]).create()
        EntityList afterList = ec.entity.find("moqui.security.ArtifactAuthzCheckView")
                .condition("userGroupId", "ALL_USERS").useCache(true).list()
        ev.delete()
        // logger.info("ArtifactAuthzCheckView before (${beforeList.size()}):\n${beforeList}\n after (${afterList.size()}):\n${afterList}")

        then:
        afterList.size() == beforeList.size() + 1
        afterList.filterByAnd([artifactGroupId:"SCREEN_TREE"]).size() == 3
    }

**Comment by jonesde** [comment]
This is fixed in commit #0a78a3d. The approach may be overly broad, i.e. clear view-entity list cache entries that don't need to be, but handles it anyway. Apologies for the cluttered commit, the main new thing is the EntityCondition.mapKeysNotContained() method and the EntityCache use of it.
