### ISSUE TITLE
Question: is there a way to customize the built-in export to CSV (comma separator, encoding)

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#125]
Is there an option to customize the way Moqui renders a CSV file?

I have a screen with form-list and a built-in CSV export.
![image](https://cloud.githubusercontent.com/assets/14863763/18943895/aaf503a8-8622-11e6-9580-9f9624b87d44.png)

![image](https://cloud.githubusercontent.com/assets/14863763/18943897/ae4770e0-8622-11e6-82e5-a6a22d88722a.png)

The output is a CSV file encoded in UTF-8 with comma used as a separator. Which casues problems to my Excel, opening it directly. See more details http://stackoverflow.com/questions/39728027/exporting-to-csv-using-built-in-tools-incorrect-characters/39762854#39762854.

**Comment by jonesde** [comment]
What would you propose to change? I don't have Excel on Windows to test it with so can't help with testing that. From what you wrote it seems like as long as you tell it the character encoding is UTF-8 it works fine.

**Comment by mrovnanik** [comment]
Yes it works fine, when you import the file manually. But in reality, when user generates the CSV file and the file is downloaded via the browser, he/she subsequently clicks on the file.

Of course, I can try to tweak it on the Excel side (or live with it), I was just wondering whether I can change the way the file is generated.

By default, the file is opened as this. Excel even does not separate columns, as in our regional settings, usually semicolon is used as a separator:
![image](https://cloud.githubusercontent.com/assets/14863763/18955232/cb833890-8656-11e6-8da1-d87da9d9e7d8.png)

**Comment by jonesde** [comment]
Anything can be changed... it's just a question of what sorts of changes to make. Opening a UTF-8 file with a different encoding is always going to cause problems (in this case it isn't just the separator, it is also various characters that get messed up). When you open it directly from the browser after download does Excel show a dialog allowing a change of the character set, ie to tell Excel that it is a UTF-8 file?

**Comment by mrovnanik** [comment]
No, it just opens it right away and tries to parse the data. No dialog to confirm/change the character set.

**Comment by mrovnanik** [comment]
David, you can let it be. I did not want to complicate the code base. It is an "issue" I can live with.
