### ISSUE TITLE
Redirecting from one screen to another

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-framework#135]
I need to redirect from one screen to another in some cases, for which I am attempting to use the sendRedirectAndStopRender method in the ScreenRenderImpl.groovy. In the comment it says that "this should be called as part of a always-actions or pre-actions block to stop rendering before it starts".
Now, I have not found any way to access this method from the always-actions or pre-actions sections in the screens, is there any?

**Comment by jonesde** [comment]
When screens are rendered there is always a context field with the name "sri", so you can call this or other methods in always-actions or pre-actions using:

<script>sri. sendRedirectAndStopRender(myUrl)</script>

This is an internal method and not part of the ScreenRender interface, so less care is taken over time ensuring the methods stay consistent. This one is not likely to change, but just a general word of warning when using any of the org.moqui.impl.* classes.

Did you try this and ran into some sort of error? In general using the script element is the way to do anything you can't with the other XML Actions elements.

**Comment by jenshp** [comment]
I had not tried it, works now, thanks!

**Comment by ronankeane** [comment]
Sorry to bump this but was there some code in David's answer that failed to render? Can sendRedirectAndStopRender be called through "sri"? Thanks.

**Comment by jenshp** [comment]
No, it renders OK up to the point where you redirect and then starts rendering the (internal) URL to which you wanted to direct.
Just use "sri.sendRedirectAndStopRender(url)" inside a script block and it works fine.
