### ISSUE TITLE
ServiceRun does not handle Timestamp parameter type

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-framework#137]
When attempting to run any service that has a Timestamp type parameter through the /apps/tools/Service/ServiceRun screen, an error appears and the date time selector does not work. This happens for example with the ootb org.moqui.impl.BasicServices.echo#Data service.

The error is attached.
[error-Timestamp.txt](https://github.com/moqui/moqui-framework/files/529666/error-Timestamp.txt)

**Comment by jonesde** [comment]
Sorry it took a while to get to this. I just tried it with the latest code (ServiceRun screen with the echo#Data service, selecting and passing in a date/time) and it worked fine.

I don't know what might have changed to fix it, or if I am simply seeing a different result. Please try it with the latest code and if you are still seeing the error let me know if you are doing something different from what I described above, ie more specific steps to reproduce.

**Comment by jenshp** [comment]
Yes, it is working with the current code now.
