### ISSUE TITLE
Sequence issues when restoring records into tables in H2

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-framework#138]
When restoring records into tables, the sequences are not updated, so afterwards I get attempts to create new records with already existing primary keys. This is using the standard h2 database.
Is there a way to update the sequences, either specifying them in the entity XML, automatically or when checking the tables, so that they are at least as big as the biggest primary key already in the table?

**Comment by jenshp** [comment]
It seems I was missing the moqui.entity.SequenceValueItem in the restoring, checking now.

**Comment by jonesde** [comment]
Did you find a solution? This is always a tricky issue, migrating data from one system to another. The new entity data snapshot features with a screen in the Tools app makes this much easier (streams DB data directly to a zip file, can upload and load a zip file from that screen in a service job or from command line which is easiest with the new 'raw' option, run 'java -jar moqui.war help' for details). Unless you have safe cherry picked records to import in general it is best to only import in bulk (like with snapshots) into a fresh system. The new snapshot tool is nice for replicating systems, backup, etc but I don't know how well it will do with really large databases... there is a limit somewhere (depending on the hardware it is running on and such) as to how big a database can be exported and stored in one big zip file. Going directly to/from zip files helps a lot with the file size, especially with XML export/import which is what it uses (best for handling large text, encoded binary values, etc).

Key management is tough between systems. Moqui has config options (in the Moqui Conf XML file) to prefix all sequenced PKs which makes it easier. A prefix on load option would be nice, but not easy to implement (could be done across all sequenced fields for consistency, ie make sure foreign key fields on other entities are prefixed as well to maintain referential integrity).

**Comment by jenshp** [comment]
It worked, just had to check the values in moqui.entity.SequenceValueItem so there would not occur any pk collisions, restart and nothing else.
In this case, for migration from a moqui-1.6.3 pre-release to current moqui-2.0.0 I made a small service to export data using the ec.entity.makeDataWriter() and passing the relevant entity names in the correct order for later restoring. Adding the missing entity with sequence values was all I was missing.
