### ISSUE TITLE
strange Error message with moqui-plus-runtime.war

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#140]
__Problem__
I got this problem when running Moqui in docker (use included dockerfile) and do something that make Moqui raise an exception.
For example: I create an Order with every field is blank (due to no loading demo data) and get this error message displayed in OrderDetail screen:
`Error rendering screen [component://SimpleScreens/screen/SimpleScreens/Order/OrderDetail.xml]: java.lang.NoSuchMethodError: org.apache.logging.log4j.core.util.Loader.loadClass(Ljava/lang/String;)Ljava/lang/Class; `

Consol output:
```
Error rendering screen [component://SimpleScreens/screen/SimpleScreens/Order/OrderDetail.xml]: java.lang.NoSuchMethodError: org.apache.logging.log4j.core.util.Loader.loadClass(Ljava/lang/String;)Ljava/lang/Class; 

09:12:23.487 ERROR 989780873-13                      o.m.i.a.XmlAction Error running groovy script (java.lang.NullPointerException: Cannot get property 'partyId' on null object): 
...
Exception in thread "AsyncAppender-AsyncLog" java.lang.NoSuchMethodError: org.apache.logging.log4j.core.impl.ThrowableProxy.getExtendedStackTraceAsString(Ljava/util/List;Lorg/apache/logging/log4j/core/pattern/TextRenderer;)Ljava/lang/String;
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:68)
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
...
```

__Test with `gradlew run`__

Then I try the same thing in my project workspace:
Error message display in OrderDetail screen:
`Error rendering section [OrderPartSection] in screen [component://SimpleScreens/screen/SimpleScreens/Order/OrderDetail.xml]: java.lang.NullPointerException: Cannot get property 'partyId' on null object`

This message is normal. The consol output also doesn't have `java.lang.NoSuchMethodError` exception

__Run moqui-plus-runtime.war in working environment again__
Do the same scenario in working environment, but using `-jar moqui-plus-runtime.war`

Error message display in OrderDetail screen: `[Template Error: org.apache.logging.log4j.core.util.Loader.loadClass(Ljava/lang/String;)Ljava/lang/Class;]`

Consol output: neither logging message nor Exception traces are display like nothing happened

Although this issue doesn't stop system from running, but this behavior may make developer difficult to debug the system issue if any

**Comment by locnguyenx** [comment]
I've found a problematic jar `elasticsearch-5.0.0-rc1.jar`, which is in WEB-INF/lib of moqui-plus-runtime.war
When move it out and put back to `/runtime/component/moqui-elasticsearch/lib`, the exception with log4j disapears.

**Comment by jonesde** [comment]
Thanks for looking into this. The change to use ElasticSearch 5.0.0-rc1 is very recent and I hadn't tested again on Docker yet. The best solution may be to change the moqui-plus-runtime.war file to leave the jar files in the component/lib directories. I'm not sure why this is happening with all the jars in the WEB-INF/lib directory, but there are some significant changes in ElasticSearch 5 and they really do some weird stuff with jar loading.

**Comment by locnguyenx** [comment]
I'm fine with this workaround. May I close this issue?

**Comment by jonesde** [comment]
It looks like there is more to it than just leaving the jar files in the components, there is an actual issue here where ElasticSearch, very annoyingly (like some other odd engineering decisions they have made in the last year) overrides ThrowableProxy in log4j core and uses a method that was removed in Log4j 2.7. It looks like we'll have to stick with log4j 2.6.2 for now, until this is changed in ElasticSearch.

**Comment by jonesde** [comment]
In commit #a64ff74 I moved back to log4j 2.6.2 (instead of 2.7) and that resolves this issue, errors with stack traces are now logged as intended.
