### ISSUE TITLE
Sending of moqui.basic.email.EmailMessages in ES_READY status

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-framework#142]
When sending messages using the org.moqui.impl.sendEmailTemplate.groovy implementation and there is a failure, the message would be created and be left in "ES_READY" status in the moqui.basic.email.EmailMessage entity. In this case, and with manually created EmailMessages as well, it would be useful to have a service that takes all messages in ES_READY and attempts to send them, probably up to a certain number of attempts or within a defined time range.

Is there such a service, or some effort underway to provide it?

**Comment by jonesde** [comment]
I don't have any plans to create such a thing, might be useful though. What sorts of failures are you seeing this with, and if the failure is critical does it even make sense to try again?

**Comment by jonesde** [comment]
There is now a service for this (send#EmailMessage) added in commit #e6264f67.
