### ISSUE TITLE
[question] Could Service Rest Api support pre-action service call? 

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#143]
With Moqui screen, we can put a service-call in pre-action section to setup initial value for user context, which is used later by other services or Moqui framework. 

For example, call "mantle.party.PartyServices.setup#UserOrganizationInfo" in root screen's actions as guideline in PopCommerce to apply MANTLE_ACTIVE_ORG filter.

Could Service Rest Api support this feature?

**Comment by jonesde** [comment]
Perhaps, but IMO that is better handled by individual services. In the REST API services are mapped to an hierarchy for structural purposes only. They are very different in nature and I don't see very many of the concepts from the screen hierarchy making their way into the REST API hierarchy. REST APIs are just that, APIs, they are do not represent applications and applications will typically be structured VERY differently from the APIs they use. Common logic across sections of an application, or an entire application, is better handled at the application level than the API level.
