### ISSUE TITLE
Results when do find on view-entity are not consistent

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#149]
I setup 5 testcases as following on a view-entity, i.e mantle.party.PartyDetailAndRole:

test 1 - create Party only, don't create related entity record
```
@Share
String partyId = '100000'
 def "create Party"() {
        when:        
        ec.entity.makeValue("mantle.party.Party").setAll([partyId:partyId]).createOrUpdate()
        EntityValue outValue = ec.entity.find("mantle.party.Party").condition([partyId:partyId]).one()
        then:
        assert outValue != null
    }
```
test 2
```
def "find View-Entity with entitycache"() {
        when:

        EntityFind ef = ec.entity.find("mantle.party.PartyDetailAndRole")
        EntityValue party = ef.condition([partyId:partyId]).one()

        then:

        assert party == null
    }
```
test 3
```
    def "find View-Entity with entitycache and have selectFields"() {
        when:

        EntityFind ef = ec.entity.find("mantle.party.PartyDetailAndRole")
        ef.selectField("partyId,pseudoId")
        EntityValue party = ef.condition([partyId:partyId]).one()

        then:

        assert party == null
    }
```
test 4
```
    def "find View-Entity with entitycache and dont use cache"() {
        when:

        EntityFind ef = ec.entity.find("mantle.party.PartyDetailAndRole").useCache(false)
        EntityValue party = ef.condition([partyId:partyId]).one()

        then:

        assert party == null
    }
```
test 5
```
    def "find View-Entity with entitycache and dont use cache and have selectFields"() {
        when:

        EntityFind ef = ec.entity.find("mantle.party.PartyDetailAndRole").useCache(false)
        ef.selectField("partyId,pseudoId")
        EntityValue party = ef.condition([partyId:partyId]).one()

        then:

        assert party == null
    }
```
Testcase 5 is fail.

Hence, this is my assumption about how Moqui does entityfind:
- If entity cached not applied (entity is never cache or useCache = false):
    + if no `selectField`: all member entities will be joined
    + if `selectField` exist: all member entities which contains `selectField` will be joined
- If entity cache is applied:
    + all member entities will be joined even if `selectField` exist or not

I don't know if this is a bug or not.

**Comment by jonesde** [comment]
This behavior is documented and what you described seems correct for the intended behavior. There are sections on this in the Making Apps with Moqui book and other places.

Stated more generally, and more accurately, if you don't specify fields to select EntityFind selects all fields on the entity, or view-entity. For all view-entity queries the member-entities are automatically trimmed based on the fields selected (and the order by and condition fields if there are any that are not selected).

In general when reporting issues there are 3 things we need:

1. steps to reproduce
2. what happened
3. how what happened is different from what you expected

For this issue it would be helpful to have more about #3 in that list, ie what did you expect to happen in these cases (might be a bug) or what would you prefer to have happen (might be an enhancement request)?

**Comment by locnguyenx** [comment]
I expected that testcase 3 and testcase 5 must have the same results. According to your explanation, testcase 3 must be FAIL. However, in my test it's PASSED.
In my assumption in the first post, there's difference in behavior of finding entity with cache in Testcase 3 (PartyDetailAndRole is defined with attribute cache="true") and without cache in Testcase 5 (.useCache(false))

**Comment by jonesde** [comment]
There is one important difference between case 3 and case 5: case 3 is cached (PartyDetailAndRole has cache=true) so all fields are selected (fields to select are ignored for cached finds), but case 5 is not cached so it selects only those 2 fields.

The important thing to understand is that fields to select are always ignored for cached finds because otherwise some code may specify fields to select and if that is run first then other cached finds for the same entity and conditions without fields to select would have false null values. In general it doesn't make sense either to limit the fields selected for cached finds.

**Comment by locnguyenx** [comment]
It's clear for me now. Thanks for you comprehensive explanation.
