### ISSUE TITLE
Support multiple semaphores per service with a semaphore key

### ISSUE THREAD

**Issue by lektran** [moqui/moqui-framework#16]
I've often come across situations where I wish I could declare a semaphore for a certain service context rather than globally locking against the service name.

An example might be a service that pulls in data from external sources where an input parameter (datasourceId) defines which external source to pull from.  If this service runs hourly against each datasourceId but sometimes an import takes longer than an hour, then you end up with two executions of the service trying to pull in from the same datasourceId.  It would be nice if you could fail the 2nd call to that datasourceId but allow instances of the service to run against other datasourceIds.

**Comment by jonesde** [comment]
This wouldn't be too hard to implement, especially for a single key. For multiple keys (or the entire context) it would be more difficult because they all need to sit on the DB record and it's help for querying to have the key on a field/column.

I agree the scenario is pretty common. What I'd propose is a new service element attribute to specify the semaphore key field, and add a field to the service semaphore entity for the key field's value. If the attribute is populated the field value would be pulled from the context and saved with the semaphore, and the semaphore check query would filter by it too.

**Comment by lektran** [comment]
It looks like it would need to form part of the primary key on the entity, how are you handling changes to those currently?

I think a single field key would be fine initially.

**Comment by jonesde** [comment]
I don't have a good (well, automated anyway) solution for dealing with PK changes to existing entities. Most of those to date have happened in mantle-udm or when the project was very young so I didn't care as there were no production instances to maintain. The intention has been to use either LiquiBase to elements like its elements within entity definitions. The main issue with LiquiBase is it's meant to be used from a starting database and has forward moving updates, as opposed to having a current state definition and updates to move to the current from past versions.

Anyway, in this case it's not an issue as on second glance a separate table will be necessary anyway. In some cases we'll want one PK field and in others 2... and with we can't use the 2 PK entity for one PK records with a null value (we could use a placeholder value I suppose... but that's messy in its own way).

I'll start an initial version of this...

**Comment by jonesde** [comment]
An initial version of this is in commit #cc61bda (I forgot to add the issue # to it so it won't show up here automatically). I tested it with the poll#EmailServer service, uncommenting the job in quartz_data.xml to run it.

Let me know if that works for you, and of course a second set of eyes on it is always helpful.

**Comment by lektran** [comment]
Looks good to me, thanks David!  It'll be a little while until I can try it out, I still actually have to port the code over.  I'll close this issue and open a new one if any issues come up.

The other thing I haven't seen in the code is something to track which Moqui instance is holding the semaphore so it can be cleaned up on restart if the instance goes down.  It was added to OFBiz a while back I think.  Not a concern for me right now, just an FYI.
