### ISSUE TITLE
Issue while edit WikiPage with unicode

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#163]
**Problem:**
I edited a WikiPage which has rootPageLocation is "component://...", i.e DEMO/Demo Page 1, and key in some unicode words.
After save this new content, the page redloaded in which unicode charaters are changed (I think they are not encoded correctly).
Try edit the wikiPage file externaly with the same unicode content, this wikiPage is loaded and display correctly as expected.

**Suggested solution:**
change problematic method in `UrlResourceReference.java`
```
public void putText(String text) {
        if (!isFileProtocol) {
            final URL url = locationUrl;
            throw new IllegalArgumentException("Write not supported for resource [" + getLocation() + "] with protocol [" + (url == null ? null : getUrl().getProtocol()) + "]");
        }

        // first make sure the directory exists that this is in
        File curFile = getFile();
        if (!curFile.getParentFile().exists()) curFile.getParentFile().mkdirs();
        // now write the text to the file and close it
        try {
            /* existing code */
            /*
            FileWriter fw = new FileWriter(curFile);
            fw.write(text);
            fw.close();
            */
            /* new code */
            Writer fstream = new OutputStreamWriter(new FileOutputStream(curFile), StandardCharsets.UTF_8);
            fstream.write(text);
            fstream.close();

            this.exists = null;
        } catch (IOException e) {
            throw new BaseException("Error writing text to file " + curFile.getAbsolutePath(), e);
        }
    }
```

This fix works for my issue. However, I wonder if it have any impact to other Moqui functions.

**Comment by jonesde** [comment]
Thank you, this fix is in commit #730dc8d. FileWriter picks up the default character set and if it is not UTF-8 then you would see this issue, so specifying it explicitly in this way is a good fix.
