### ISSUE TITLE
clone task

### ISSUE THREAD

**Issue by mckhoi** [moqui/moqui-framework#167]
Hi Moqui Team,

I cloned a task and forgot to assign someone. How can I find it on my task list to assign later?

Thanks for your greate work.
Best regards from Stuttgart, Germany.
Khoi Tran

**Comment by jonesde** [comment]
It sounds like you are talking about HiveMind or perhaps SimpleScreens, which are projects separate from moqui-framework. Moqui Framework itself is a toolset and doesn't know anything about tasks or assignments. You could provide more detail, but in general these various Moqui Ecosystem projects are open source projects meant for developers and all support is community based with no infrastructure for end user support.

**Comment by jonesde** [comment]
As a side note, if you are using HiveMind you can search for all tasks using the Tasks link (there are two on the dashboard, one above My Tasks and one to the left with an icon).
