### ISSUE TITLE
Calendar translation

### ISSUE THREAD

**Issue by mckhoi** [moqui/moqui-framework#174]
Translations for "Today", "Day", "Month", "Year"... on the Calendar does not work.
http://localhost:8080/apps/my/User/Calendar

**Comment by jonesde** [comment]
This is an issue for the SimpleScreens repository as nothing there, not even the JavaScript library used, is part of moqui-framework (or even moqui-runtime). Please file an issue under SimpleScreens and I'll comment more there. I can say without looking into it more that this is an enhancement (as opposed to a bug, as it is not something already implemented) and will depend on what the fullcalendar JS library supports. There is probably a way to do it, but I don't know off the top of my head.
