### ISSUE TITLE
[VueJS] Authorization issue with pre-actions

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#175]
I'm trying to do retrofitting for PopCommerceRoot to make it work with VueJS, and get ArtifactAuthorizationException when navigate to url `/popc/Product/Detail/DEMO_UNIT/Demo-Product-One-Unit`

Problematic code in ScreenRenderImpl.groovy:
line [L698](https://github.com/moqui/moqui-framework/blob/23ead83839053576be3438b1c2ce8e3bc6c46185/framework/src/main/groovy/org/moqui/impl/screen/ScreenRenderImpl.groovy#L698)
line [L1488](https://github.com/moqui/moqui-framework/blob/23ead83839053576be3438b1c2ce8e3bc6c46185/framework/src/main/groovy/org/moqui/impl/screen/ScreenRenderImpl.groovy#L1488)

Current code assumes that the first 2 paths in url will be **webroot** and **apps**, skips them and starts run `recursiveRunActions` from component root (which is already granted appropriate permission).

However, in case of PopCommerceRoot, the paths will be: webroot/popc

I suggest a modification like this:
at L698:
```
// preActionSds = new ArrayList<>(screenUrlInfo.screenPathDefList.subList(2, screenUrlInfo.screenPathDefList.size()))
// only skip 1 if the root screen not linked to apps
                if (screenUrlInfo.screenPathDefList[1].location.endsWith('apps.xml'))
                    preActionSds = new ArrayList<>(screenUrlInfo.screenPathDefList.subList(2, screenUrlInfo.screenPathDefList.size()))
                else
                    preActionSds = new ArrayList<>(screenUrlInfo.screenPathDefList.subList(1, screenUrlInfo.screenPathDefList.size()))
```

at L1488:
```
// ArrayList<ScreenDefinition> preActionSds = new ArrayList<>(fullUrlInfo.screenPathDefList.subList(2, fullUrlInfo.screenPathDefList.size()))
// only skip 1 if the root screen not linked to apps
ArrayList<ScreenDefinition> preActionSds
        if (fullUrlInfo.screenPathDefList[1].location.endsWith('apps.xml'))
            preActionSds = new ArrayList<>(fullUrlInfo.screenPathDefList.subList(2, fullUrlInfo.screenPathDefList.size()))
        else
            preActionSds = new ArrayList<>(fullUrlInfo.screenPathDefList.subList(1, fullUrlInfo.screenPathDefList.size()))
```

**Comment by jonesde** [comment]
How would this help? For the WebrootVue.js stuff to work with mount points different from /vapps and /apps you would need a pair of root screens like vapps.xml and apps.xml, and you would want to skip the first 2 screens in the path so the pre-actions (like those in PopCommerceRoot.xml) don't run and try to populate html_scripts, html_stylesheets, etc.

**Comment by shendepu** [comment]
@locnguyenx there is no issue to access  `/popc/Product/Detail/DEMO_UNIT/Demo-Product-One-Unit` with latest code. 

you may clear browser cache, especially access vapps after access apps, in case that there are resource loaded from browser cache.

**Comment by jonesde** [comment]
BTW, there is a more general issue with the current WebrootVue.js stuff... in various places it assumes there is a user authenticated so more significant changes may be needed to work with something like the /popc screens where many don't require an authenticated user.

The most important point is that the WebrootVue.js file is designed for running internal apps that are mostly made up of full XML Screens that make use of the XML Forms and such. For an ecommerce app various things should really be quite different, and for real-world ecommerce sites the PopCommerceRoot and subscreens are really not the recommended pattern. Typically you would use few or no XML Forms and such, instead using custom HTML in FTL templates. For a more dynamic site (client/browser rendered) it might as well be more similar to a typical SPA instead of doing all the crazy stuff that WebrootVue.js does to handle menus, lazy screen loading, supporting a mix of client and server rendered screens, etc, etc.

**Comment by locnguyenx** [comment]
Thanks for your explanation. I haven't noticed that pre-actions scripts in PopCommerceRoot.xm should be skipped in such scenario.
So, there's a workaround solution is that sub-screen of popc will be allowed anonymous-view.

The website that I'm building is not really for ecommerce. However, to get better customer journey, users should jump to a landing page instead of seeing the application selector at home page. The current screens navigator isn't needed too.
The constraint about authenticated user of Vuejs might be an issue, as I need anonymous access to some pages.

**Comment by jonesde** [comment]
If you're not using the menus (and the getMenuData) various other things might work without a user authenticated, but changes to the JS will be needed as well. The router and screen renderer in WebrootVue.js uses the menu data to know which screen to download and render in the subscreens-active Vue component that is the placeholder for subscreens.

In theory you can do whatever, but the more you vary from what these are designed for you'll have to write code that does something different. That may sound silly to say out loud, it's always the case with code...
