### ISSUE TITLE
javacript error with WebSocket and https

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#177]
When deploy Moqui using https, I got this error in javascript console:
```
WebSocket connection to 'ws://localhost:8443/notws' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE
```
I've checked and found problematic code in apps.xml:
```
<render-mode><text type="html"><![CDATA[<script>var notificationClient = new moqui.NotificationClient("ws://${ec.web.getHostName(true)}${ec.web.servletContext.contextPath}/notws");</script>]]></text></render-mode>
```
In fact, I don't know much about WebSocket, so I'm not sure if this error is critical or not. However, after research about this problem, I changed to code below and no error occured:
```
<render-mode><text type="html"><![CDATA[<script>
        var wsProtocal = "ws";
        if (location.protocol === 'https:') {
            wsProtocal = "wss";
        }
        var notificationClient = new moqui.NotificationClient(wsProtocal + "://${ec.web.getHostName(true)}${ec.web.servletContext.contextPath}/notws");</script>]]></text></render-mode>
```

**Comment by jonesde** [comment]
Thank you for bringing this up, a similar improvement is in place in moqui-runtime commit #74b494b (this is really a moqui-runtime thing, as a general guideline there is nothing for websocket client or other web client UI stuff in moqui-framework).
