### ISSUE TITLE
Error to delete a resource file in Sytem Resource Finder

### ISSUE THREAD

**Issue by hexd-moshi** [moqui/moqui-framework#178]
In System"Resource Finder", there is error message "Invalid backend response. Data is not JSON" when to delete a resource file

**Comment by hexd-moshi** [comment]
The test resource is a Excel file

**Comment by hexd-moshi** [comment]
After more checking, there is a relationship when to do ResourceReference.delete() in table dbResourceFileHistory. 
Below is the solution
`<script><![CDATA[
                    org.moqui.context.ExecutionContext ec = context.ec
                    ResourceReference newRr = ec.resource.getLocationReference("${attachment.attachmentLocation}")
                    ec.entity.find("moqui.resource.DbResourceFileHistory").condition("resourceId", newRr.getDbResourceId()).one().delete()
                    newRr.delete()
                ]]></script>`

**Comment by jonesde** [comment]
Thank you for reporting this. Looking deeper it appears to be an issue specifically with the DbResourceReference.delete() which wasn't deleting history records before trying to delete the file record. That is fixed in commit #5acd700.
