### ISSUE TITLE
get clientIpAddress from request Header "X-Forwarded-For"

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#179]
Problematic code: [L189](https://github.com/moqui/moqui-framework/blob/97eb01ed35291e06bea2ea5407dc2e997934a2a5/framework/src/main/groovy/org/moqui/impl/context/UserFacadeImpl.groovy#L189)

If Moqui is behind some proxy servers, value of X-Forwarded-For will be a list of IP delimited by comma.
In this case, method `InetAddress.getByName(visit.clientIpAddress)` in ServerService.get#VisitClientIpData will throw exception.

Suggest to get the first left IP of X-Forwarded-For header:
```
parameters.clientIpAddress = request.getHeader("X-Forwarded-For")?.split(',')?.getAt(0)
```

**Comment by jonesde** [comment]
This is a minor issue, just for the Visit history. It might be nice to have all proxy IP addresses, but agreed that just the original is most useful here. I made similar changes in commit #061f93d.
