### ISSUE TITLE
Support sort on text field on Data Document

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#183]
The field type in Entity definition is mapped to different elastic search field type. `id`, `id-long` and `text-indicator` is mapped to `keyword`, other text type like `text-medium` is mapped to elastic search `text`. But by default elasticsearch text type is not sortable. 

Is it possible to added a field `keyword` (or `esTypeMapping` where may contain `keyword,range` of elasticsearch field type separated by comma) in entity `DataDocumentField`, so component `moqui-elasticsearch` can know what additional field type need to be created when creating index mappings.

**Comment by shendepu** [comment]
And if this approach is ok, I can implement it in both framework (extend DataDocumentField definition) and moqui-elasticsearch.

**Comment by jonesde** [comment]
How to configure it is one question, but the first question is what is the solution in ElasticSearch to this issue. One problem with the keyword type is that it is not tokenized for search so only matches on the full string. One possible solution to this is something like this:

https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html

This adds a little complexity (ie having to sort on 'city.raw' when the field is of a type with both) but makes it much more flexible. 

I've thought about this a bit over time and looked a little into options in the latest ElasticSearch, unfortunately the mapping types have changed over time and this problem introduced with more recent versions of ES.

**Comment by shendepu** [comment]
Yes, multi-fields in elasticsearch is the way to go. text type field in entity definition still has the `text` type which is for full text search. 

```
 {
  "city": {
    "type": "text",
    "fields": {
      "keyword": { 
        "type":  "keyword"
      },
      "range": {
        "type": "integer_range"
      }, 
      ...
    }
  }
}
```

but key in fields is more like `keyword`, `range` which can tell the type it refers to. https://www.elastic.co/guide/en/elasticsearch/reference/5.2/fielddata.html It seems not handy to use `city.keyword` to do sorting.

**Comment by shendepu** [comment]
Besides of additional field data types, there are also common use cases:

- Use `html_strip` character filter to strip out HTML elements if field text is html
- Analyze field text in different language other than English.

these two use cases are essentially how to define custom analyzer on Field, the analyzer need to exist first. It will need to add custom settings to customize analyzer.

One more use case for multi-language content: some of text can be localized, but they are indexed with original text. Maybe a `locales` field can be added, and then auto added field with suffix of locale in index, e.g. field name of `title` in locale `zh_CN` to be `title_zh_CN`, then application can get corresponding localized context based user locale setting

**Comment by shendepu** [comment]
When i think about extending field mapping with custom analyzer, it seems a more general approach better than defining types on `DataDocumentField`. 

Add a DataDocumentIndexSetting entity to configure settings on index, Add a DataDocumentFieldMapping entity to configure any allowed mapping on field. 

The addition types could be done with `fields` mapping with this approach, and any mapping parameters in https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-params.html can be configured on field. 

I am trying this approach. so the current two PRs may be hold.

**Comment by jonesde** [comment]
I see the utility of what you originally proposed and in the pull requests you created, and it is nice to have these defined along with the DataDocument.

At a certain point it is not worth making this more complex, or eventually getting to a structure that supports anything that ElasticSearch supports. Mappings can be added or modified directly in ElasticSearch, Moqui doesn't have to do it (just like with database meta data). In general Moqui tries to support the most general and useful things, and leaves lower level and more involved stuff to the underlying tool itself.

I'll hold off and review whatever you have in mind, but my inclination is to go with the approach in your 2 pull requests and leave the rest for managing directly with ElasticSearch.

**Comment by shendepu** [comment]
I have created another two pull requests https://github.com/moqui/moqui-framework/pull/186 and https://github.com/moqui/moqui-elasticsearch/pull/7 which looks clean. 

By adding entity DataDocumentFieldMapping, it is more extensible than adding esDataTypes on DataDocumentField.

**Comment by jonesde** [comment]
This has moved to the moqui-elasticsearch issues and pull requests, so closing this issue.
