### ISSUE TITLE
<entity-find-one> with force-update does not work on entity with cache in definition

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#184]
I try to use

```
<entity-find-one entity-name="moqui.security.UserGroupPermission" value-field="ugp" for-update="true"/>
<set field="ugp.thruDate" from="ec.user.nowTimestamp"/>
```
to set thruDate, it throws exception of `Error running groovy script (org.moqui.entity.EntityException: Cannot set field thruDate, this entity value is not mutable (it is read-only)): ` 

The entity definition of UserGroupPermission has cache defined.
```
<entity entity-name="UserGroupPermission" package="moqui.security" use="configuration" cache="true" short-alias="userGroupPermissions">  
```

from the documentation of entity-find-one.@for-update `If this is true the cache will not be used, regardless of the cache attribute here and on the entity definition.` it is supposed that with for-update the entity value should be updated. 
```

            <xs:attribute name="for-update" type="boolean" default="false">
                <xs:annotation><xs:documentation>
                    Lock the selected record so only this transaction can change it until it is ended (committed or
                    rolled back). This does not have to be set to true in order to update the record, it just keeps
                    other transactions from updating it. In SQL this does a select for update.

                    If this is true the cache will not be used, regardless of the cache attribute here and on the
                    entity definition.
                </xs:documentation></xs:annotation>
            </xs:attribute>
```

Can `for-update` bypass the cache configuration on entity definition?

**Comment by jonesde** [comment]
Thank you, this is a definitely a regression. It is fixed in commit 8b55fd2 which also has an automated test to make sure this doesn't get lost in future changes. I don't know when I broke this, but the EntityFindBase.shouldCache() method has gone through quite a few revisions and this may have been broken in the 2.0.0 release.
