### ISSUE TITLE
Field value fetched by getFieldValueString causes the input (number) not to work properly for other than US Locale

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#189]
This is possibly only a question.

I noticed this behavior when implementing an input of type="number". As to what is displayed via the generated HTML, I suppose the function ScreenRenderer's **getFieldValueString** function fetches the field value. When using an account with the US Locale, evertyhing works correctly and value is displayed correctly in the input. After switching to Sloval Locale, there is a problem. The value is loaded into the input's value attribute, but with comma as decimal separator (opposed to dot when using the the US Locale), but is not displayed.

![input_number_sk](https://cloud.githubusercontent.com/assets/14863763/23335814/a06d0938-fbbd-11e6-9850-fd0c3b79c584.png)
![input_number_us](https://cloud.githubusercontent.com/assets/14863763/23335815/a1ed34cc-fbbd-11e6-931d-cf3b18ed3509.png)

Has anyone come accross such behavior? If yes, which way to go?

**Comment by jonesde** [comment]
This has been an issue for a long time, but better support for locales with a comma and period switched isn't a priority for me, and though it has been reported to my knowledge no work on it has been done (or at least contributed). See Issue #49 

https://github.com/moqui/moqui-framework/issues/49

**Comment by mrovnanik** [comment]
OK
