### ISSUE TITLE
simplifyRequestParameters@WebUtilities.java causes a string with comma to change to an array

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#194]
The behavior is like this - if an input contains text with a comma, the parameter is treated as an array and causes problems:

This is how it looks like when the parameter does not contain a comma:
![image](https://cloud.githubusercontent.com/assets/14863763/23666232/c10e17fa-035a-11e7-8ac1-d261daad4f7f.png)

And when the comma is in the text:
![image](https://cloud.githubusercontent.com/assets/14863763/23666301/e76b85ae-035a-11e7-8821-48c78ae8196e.png)

The issue is caused by this code:
![image](https://cloud.githubusercontent.com/assets/14863763/23666329/fe8b06ba-035a-11e7-98c1-2c2a3b825af0.png)

**Comment by jonesde** [comment]
This code went into git temporarily and has been updated/fixed already. Just pull from git again.
