### ISSUE TITLE
moqui third part login

### ISSUE THREAD

**Issue by fuxiaofengfu** [moqui/moqui-framework#213]
<img width="505" alt="282362ab-51bd-4759-9e80-37e764fa06eb" src="https://cloud.githubusercontent.com/assets/12025286/26309244/da705be4-3f2e-11e7-8f50-4224ac3ac239.png">

![f75dbe51ba5a6297e0d9d2687ba13151](https://cloud.githubusercontent.com/assets/12025286/26309058/2952c8f6-3f2e-11e7-8236-c7a55da0d319.png)
![753fddf291943d5c1e93707db487853d](https://cloud.githubusercontent.com/assets/12025286/26309061/2b1689ca-3f2e-11e7-95d5-03064a4d802f.png)

issue:
i am doing wechat login,and how i can set moqui session,i add a method in UserFacade.class,but how to implement ? and i want to login accord to userid,how can i do ?how to deal with user roles?

**Comment by jonesde** [comment]
There shouldn't be any reason to modify UserFacadeImpl. What does an endpoint for wechat login need to look like and handle? Overall your question is impossible to answer, not enough detail.

**Comment by jonesde** [comment]
Closing, don't see an issue here and no follow up from reporter.
