### ISSUE TITLE
How to deploy moqui in external web container?

### ISSUE THREAD

**Issue by justin-wick** [moqui/moqui-framework#215]
does moqui support repackage to a new war file include my own runtime floder ?

**Comment by shendepu** [comment]
You can do it by simply run 
```
gradle addRuntime
```
 which unpacks `moqui.war`, add runtime folder, repack it as `moqui-plus-runtime.war`

**Comment by justin-wick** [comment]
thanks for you answer...Let me have a try

**Comment by jonesde** [comment]
Along the lines of what @shendepu  mentioned there is documentation for general run and deploy options on the moqui.org site:

http://www.moqui.org/framework/docs/RunDeploy.html
