### ISSUE TITLE
Swagger spec doesn't include model extentions after first request

### ISSUE THREAD

**Issue by joelschuster** [moqui/moqui-framework#217]
We have a custom component that extends the Mantle model by adding a couple of fields. The Swagger UI and swagger spec that's generated does not contain the fields _after_ the first request. On the first request we see the new fields. However, after refreshing the fields are gone.

**Comment by jonesde** [comment]
Was this a Swagger file for the Entity REST interface (/rest/e1 or /rest/m1) or for the Service REST API (/rest/s1)? To help reproduce it the actual service or entity in question would be helpful too.

The first thing I would do to look into this is to look at the entity and/or service definition in the Tools app to make sure the framework's current definition matches what you expect as that is what the Swagger text is generated from.

**Comment by joelschuster** [comment]
It was s1, I'll send along the Entity extension definition. The m1 model continues to show the fields there through multiple requests, so the underlying model seems to be consistent.

**Comment by joelschuster** [comment]
`<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="http://moqui.org/xsd/entity-definition-2.0.xsd">
    <extend-entity entity-name="Asset" package="mantle.product.asset">
        <field name="manufacturer" type="text-medium"/>
        <field name="model" type="text-medium"/>
    </extend-entity>
</entities>`

**Comment by jonesde** [comment]
Which service are you looking at under /rest/s1?

**Comment by joelschuster** [comment]
/rest/s1/mantle/assets/

**Comment by jonesde** [comment]
This is fixed in commit #89cc93cf.

The issue only occurred in dev mode where the entity definition cache has a short expiration time (or could in production mode with a manual clear of the entity definition cache). It happened when an entity definition was loaded based on a short-alias and the error was the entity location list based on short-alias didn't have all locations init.

**Comment by jonesde** [comment]
BTW, when this happened (ie once the bad entity definition was in memory based on loading the swagger def which uses the short-alias to refer to the entity) if you view the entity detail screen before the cache expires again then the fields are indeed missing there too. In other words, this was a low level issue.
