### ISSUE TITLE
entity.record.list cache not cleared when update a Entity to make it match the entity conditon.

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#22]
If the cached list not contains the original value, there will not have a ra cache entry point to key of that list, when update the original value to match the entity condition, it will not remove cached list.

**Comment by chunlinyao** [comment]
It seems no efficient method other than iterate cache keys. The following code is a unit test to detect this bug.

    def "auto cache clear for list initially not include"() {
        // update the testMedium and make sure we get the new value
        when:
        ec.entity.find("moqui.test.TestEntity").condition("testNumberInteger", 1234).useCache(true).list()
        ec.entity.makeValue("moqui.test.TestEntity").setAll([testId:"EXTST1", testNumberInteger:1234]).update()
        EntityList testEntityList = ec.entity.find("moqui.test.TestEntity")
                .condition("testNumberInteger", 1234).useCache(true).list()

        then:
        testEntityList.size() == 1
        testEntityList.first.testNumberInteger == 1234
    }

**Comment by jonesde** [comment]
Thanks Yao, there may be an issue with this. There is code for it, that does just what you describe, but perhaps there is a bug in it (and one that the current EntityFindTests catch). I've been cleaning up that code and the current code block (in EntityCache.clearCacheForValue()) and right now it only does this for creates, looks like it needs to be done for updates as well to catch field changes that cause it to now match an existing cached list condition.

Unfortunately this makes updating a record for entities where cache is used more expensive, but that's part of the deal... they should only be used for very high read to write ratios.

**Comment by jonesde** [comment]
This is fixed, and the test added, in commit #771eb5e. Right now that is in a forked repo I'm working on, will be merged soon.

**Comment by visvendra** [comment]
It's not working for `entity-find-count` (Cache is not being cleared). I am using master with latest changes.

**Comment by jonesde** [comment]
More detail than "it's not working" would be helpful... and a new issue would make this easier to track and manage than a comment on an old closed one.

**Comment by visvendra** [comment]
Added another ticket with details- [https://github.com/moqui/moqui-framework/issues/197](url)
