### ISSUE TITLE
Error rendering Log Viewer screen

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-framework#221]
The new Log Viewer screen is throwing an exception following a fresh clone. The exception thrown was "Unable to resolve class org.elasticsearch.client.Client". I was only able to resolve this by fetching the moqui-elasticsearch component:

$ ./gradlew getComponent -Pcomponent=moqui-elasticsearch

**Comment by jonesde** [comment]
This is fixed in commit #cfac3b2. With this commit and the related commit in moqui-elasticsearch that screen will only be available if the component is installed (and its seed data loaded).
