### ISSUE TITLE
Error in Swagger UI for parties services

### ISSUE THREAD

**Issue by hndykstra** [moqui/moqui-framework#228]
When attempting to view the Swagger UI for parties, I am getting an error:

500 : <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 500 Service delete#mantle.party.PartySetting not found</title> </head> <body><h2>HTTP ERROR 500</h2> <p>Problem accessing /rest/service.swagger/mantle/parties. Reason: <pre> Service delete#mantle.party.PartySetting not found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.6.v20170531</a><hr/> </body> </html> 
![moqui parties swagger error](https://user-images.githubusercontent.com/24993528/27933928-9c19224a-6260-11e7-85a2-db51b1f7cb73.PNG)

**Comment by jonesde** [comment]
Thank you, this is now fixed. This is an issue in mantle-usl and not in this repository (moqui-framework) so the fix is in commit #8410695 in the mantle-usl repository. Issues like this can be filed there in the future so the commit shows up in the timeline for the issue and such.
