### ISSUE TITLE
Question on `DataDocument.populateDataDocRelatedMap` 

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#233]
I have a question on `DataDocument.populateDataDocRelatedMap` 

https://github.com/moqui/moqui-framework/blob/master/framework/src/main/groovy/org/moqui/impl/entity/EntityDataDocument.groovy#L516

```
if (setFields && !fieldEntryKey.startsWith("(")) {
    // set the field(s)
    ArrayList<String> fieldAliasList = (ArrayList<String>) fieldEntryValue
    for (int i = 0; i < fieldAliasList.size(); i++) {
        String fieldAlias = (String) fieldAliasList.get(i)
        Object curVal = ev.get(fieldAlias)
        if (curVal != null) parentDocMap.put(fieldAlias, curVal)
    }
}

```

As I understand the fieldTree now is the structure of map and its leaf is array list of field alias which key is the single field path. so for the code 
```
Object curVal = ev.get(fieldAlias)
```
should not it be 
```
Object curVal = ev.get(fieldEntryKey)
```
since fieldAlias might not be a valid field on the entity value. 

I did not run any issue on this code yet, but I notice it when update moqui-graphql since it has a method `populateDataDocDefinitionRelatedMap` which has simliar logic as `DataDocument.populateDataDocRelatedMap`

**Comment by jonesde** [comment]
This code is messy to handle the field paths vs aliases, but no it should not be the fieldEntryKey. DataDocument results are not meant to match any entity (unless you use the newer stuff to create a dynamic view entity based on a DataDocument), they are more like a view-entity where they have their own aliased field names that often don't match the original field name.
