### ISSUE TITLE
Jackrabbit error "Could not find JCR Repository Factory..."

### ISSUE THREAD

**Issue by dhcdata** [moqui/moqui-framework#236]
Prior to 74ea60f751f3d51b975fce7424f9f245569dda4d, simply changing  
`moqui-conf.tools.tool-factory@[class=...JackrabbitRunToolFactory]` disabled value to `false` and uncommenting
`moqui-conf.repository-list.repository@[type=rmi]` would allow JCR to load properly

Since 74ea60f751f3d51b975fce7424f9f245569dda4d, the error:
`.moqui.i.c.ResourceFacadeImpl Could not find JCR RepositoryFactory for repository main using parameters: [org.apache.jackrabbit.repository.uri
:http://localhost:8081/rmi]`

is returned. Is there an additional flag to flip somewhere?

**Comment by shendepu** [comment]
I have made a PR https://github.com/moqui/moqui-framework/pull/237 to solve the issue. 

`ToolFactory.init()` runs after ResourceFacade initialization, so I move the code to `preFacadeInit`, and also check if the jackrabbit port is up. 

It seems you have to uncomment 
```
compile 'org.apache.jackrabbit:jackrabbit-jcr-rmi:2.12.1' // Apache 2.0
```
in framework build.gradle, since it does not work by adding jackrabbit-jcr-rmi jar in `runtime/classes`

**Comment by shendepu** [comment]
UPDATE: 

Here is the way to add jackrabbit-jcr-rmi without change framework build.gradle. 

1. Add `compile 'org.apache.jackrabbit:jackrabbit-jcr-rmi:2.12.1'` in dependency in build.gradle of your component
2. Add MoquiConf in your component which enables jackrabbit repository ,
```
<moqui-conf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://moqui.org/xsd/moqui-conf-2.1.xsd">
    <tools>
        <tool-factory class="org.moqui.impl.tools.JackrabbitRunToolFactory" disabled="false"/>
    </tools>

    <repository-list>
        <!-- requires 'org.apache.jackrabbit:jackrabbit-jcr-rmi' in the classpath: -->
        <repository name="main" workspace="default" username="admin" password="admin">
            <init-param name="org.apache.jackrabbit.repository.uri" value="http://localhost:8081/rmi"/></repository>
    </repository-list>
</moqui-conf>
```

**Comment by dhcdata** [comment]
Does this still require your PR?

**Comment by shendepu** [comment]
Yes. The PR is to resolve another issue of rmi connection to Jackrabbit is refused since Jackrabbit needs to be running and up before resource facade initialize and connect to repository.

**Comment by jonesde** [comment]
I believe this is resolved now that the pull request is merged.
