### ISSUE TITLE
How to support Mobile APP development

### ISSUE THREAD

**Issue by hanyou** [moqui/moqui-framework#240]
I believe Moqui is very excellent framework in web APP development, but how to support mobile APP development, How to support H5 SPA development?

**Comment by jonesde** [comment]
This is more of a topic of discussion than an issue and would be better posted in the Moqui Ecosystem group on LinkedIn.

In general if you want to build a separate application that talks to a Moqui server just use the various REST interfaces to communicate with the server.

I've never heard of H5, from a quick google search are you referring to github.com/naikus/h5? Moqui uses Vue.js (vuejs.org) for the new hybrid SPA architecture for XML Screens and it can be used for independent client applications just like Angular or React.

**Comment by hanyou** [comment]
Thank you! 
H5 means HTML5, in China we call H5.
In China, I can't access Moqui Ecosystem group on LinkedIn.

the words "Your content can not be viewed in your area." display on the page.
