### ISSUE TITLE
How to join your develop team?

### ISSUE THREAD

**Issue by hanyou** [moqui/moqui-framework#242]
I developed IT system for many years, Moqui is an excellent application framework, I can develop web application with Grails framework, so I knew groovy language, I want to join your team, how to do?

**Comment by jonesde** [comment]
Are you asking how to contribute or how to get commit/push access? There are a few roles described for the management model on moqui.org, including Contributor and Moderator. Anyone can contribute, becoming a moderator is another matter entirely and only happens by invitation when someone makes consistent high quality contributions over enough time to be trusted to review contributions and/or directly push their own changes.

For contribution just use pull requests on GitHub. This is not difficult but requires some familiarity with git and GitHub.

**Comment by jonesde** [comment]
BTW, this is more of a discussion than an issue and would be better on the Moqui Ecosystem forum on LinkedIn.

**Comment by hanyou** [comment]
I can't access  the Moqui Ecosystem forum on LinkedIn in China.

**Comment by shendepu** [comment]
LinkedIn seems disable group feature in China, so you need to use VPN to access as if it is outside of China.

**Comment by hanyou** [comment]
VPN is disabled in China.

**Comment by WillWei1983** [comment]
you can visit the url 
http://www.linkedin.com/groups/4640689
no VPN needed

**Comment by hanyou** [comment]
@WillWei1983 , thank you very much.
