### ISSUE TITLE
In the new check-out(August-9-2017) facing error at the time of Gradle Load.

### ISSUE THREAD

**Issue by RollaAshokkumar** [moqui/moqui-framework#243]
In the MoquiDemo-2.0.0 facing Error like..

Error storing entity [moqui.basic.StatusType] value (line 212): org.moqui.entity.EntityException: Error in refresh of [moqui.basic.StatusType: {statusTypeId=_NA_, description=Not Applicable}]

Caused by: org.moqui.entity.EntityException: Error in refresh of [moqui.basic.StatusType: {statusTypeId=_NA_, description=Not Applicable}]

**Comment by jonesde** [comment]
What were you doing when you saw this error, ie what are steps to reproduce it? The error messages you included are just the higher level ones that add context but don't show the actual error. You should see more detail after these, and possibly related errors before it in the log.

**Comment by RollaAshokkumar** [comment]
Thank you. The problem is with mysql-connector-java.jar. Now it is working fine.
