### ISSUE TITLE
form-list display an extra list item 

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#246]
I have only one record in `PartyStat` but the AutoFind screen display it with an extra meaningless item. 

![image](https://user-images.githubusercontent.com/4743845/29255336-f60d421e-80d2-11e7-99dc-153c9fa5032b.png)
The output of `listObject` in freemarker macro `form-list` has two items, 
But 
![image](https://user-images.githubusercontent.com/4743845/29255379-5f7b48a4-80d3-11e7-9b4c-ea0279ad2f36.png)
The `entityValueList` only has one item, also 
![image](https://user-images.githubusercontent.com/4743845/29255391-83df7e4a-80d3-11e7-9e90-86b876b3a26b.png)
sql runner return one record.

It seems that `formListInfo.getListObject(true)` returns the extra record. I haven't got time to dig deeper, so report it here.

**Comment by chunlinyao** [comment]
is it a show-total row.

Jimmy Shen <notifications@github.com>于2017年8月14日周一 上午9:34写道：

**Comment by shendepu** [comment]
Yes. it seems to be the aggregation total. 

![image](https://user-images.githubusercontent.com/4743845/29256867-1f32d282-80e0-11e7-985a-b1ea82ad6f4a.png)

but shouldn't it have no aggregation by default?

**Comment by jonesde** [comment]
Yes, the Find screen in the Auto Screens in the Tools app do this for numeric fields automatically. That was added a few weeks ago. Admittedly those screens could use some improvement (use the header-dialog for find options, hide the Edit and Delete buttons on the totals row), but no this is not a bug it was done intentionally.

**Comment by jonesde** [comment]
BTW, you can see this if you export the XML for the screen/form with the link at the bottom.

**Comment by shendepu** [comment]
Got it. Thanks!
