### ISSUE TITLE
this may cause NullPoinerException

### ISSUE THREAD

**Issue by let5sne** [moqui/moqui-framework#248]
https://github.com/moqui/moqui-framework/blob/1c55d1055b7049f6123a1b16109e049872a965a3/framework/src/main/groovy/org/moqui/impl/entity/EntityValueBase.java#L1538

in my project I found a bug named "NullPoinnerException",I change 
`return fi.name.equals(other.fi.name) && ((getValue()==null && other.getValue()==null)||getValue().equals(other.getValue()));` to fixed

**Comment by jonesde** [comment]
Thanks, this is fixed in commit #de472e03. It looks like this goes back to the Groovy to Java conversion where the automatic code isn't always correct and I missed it in the cleanups and fixes.
