### ISSUE TITLE
subscreens-item parameter

### ISSUE THREAD

**Issue by ccarlow** [moqui/moqui-framework#259]
Should subscreens-item support "parameter" child nodes?

This potential need was encountered while implementing ProductionRun screens which were based on HiveMind's Project files.  

The HiveMind Project/EditUsers.xml file seems potentially reusable by ProductionRuns.  It could possibly be moved to a WorkEffort directory under SimpleScreens and included as subscreens-item by both ProductionRun and Project.  The only thing that need would need to be supported is passing the roleGroupEnumId as a parameter with a default value to differentiate the role list between Project and ProductionRun.

Does this seem reasonable or would it be better practice to just create copies of files?

**Comment by jonesde** [comment]
From my experience over the years with reuse there are cases where it is very useful to avoid redundancy, and cases where you end up parameterizing too much or doing things like extending a form that extends another form, and then the complexity causes more problems than the extra redundancy.

If I understand correctly what you're talking about here the best approach is to have a separate screen that reuses the original in a more granular way such as including sections or extending forms from the other screen. There are examples of both of these in SimpleScreens and PopCommerce. This pattern allows the derived screen to set parameters or even query different data in its actions, depending on how the artifacts reused from the original screen are written of course. In some cases I've made changes to forms and screen sections to support parameters for specific types of reuse.

That said, the idea of parameters on subscreens-item is interesting for potentially other uses and I'm considering merging that anyway.
