### ISSUE TITLE
New jackson-databind ignores null when serialize to client

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#262]
The commit df2ee8e330f72f06fe78e4cac5c01ea3ea8512d7 and ab5df077af97295c934701f3e8d4d5b533df6793 changed to use jackson-databind. In the jackson mapper configuration, the null value is ignore, therefore not included in the json output. 

However our application relies on that the null property of json is not ignored. The exact use case is that we are using graphql api with `moqui-graphql`. The most point of graphql query is that server returns result with the data structure of client requests, no more or less. 

So if we have a query 
```
query {
   person (partyId: "100000") {
     partyId
     firstName
     birthDate
   }
}
```
And `birthDate` for the person is null, then the result should be 
```
{
  data: {
    person: {
      partyId: "10000",
      firstName: "Test", 
      birthDate: null
    }
  }
}
```
But since property with null is ignored by jackson mapper, the result is:
```
{
  data: {
    person: {
      partyId: "10000",
      firstName: "Test"
    }
  }
}
```
This causes the graphql client not working properly.

So can the jackson mapper changes to 
```
ObjectMapper jacksonMapper = new ObjectMapper()
            .setSerializationInclusion(JsonInclude.Include.ALWAYS)
```

**Comment by jonesde** [comment]
No problem, I debated whether this setting was appropriate at this lower level. Changed in commit #1118ebb3.
