### ISSUE TITLE
Config file selection with JAVA is different than ant and gradle

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-framework#27]
This is more of an observation. When I run the java, ant and gradle load commands, the java strangely picks up the PRODUCTION config file where as all others pick up the DEV file:

**ant load**
```
	[java]  Initializing Moqui ExecutionContextFactoryImpl
	[java]  - runtime directory: /Users/ayman/Desktop/moqui-framework-1.6.1-bin/runtime
	[java]  - config file: /Users/ayman/Desktop/moqui-framework-1.6.1-bin/runtime/conf/MoquiDevConf.xml
```

**gradle load**
```
	Initializing Moqui ExecutionContextFactoryImpl
	- runtime directory: /Users/ayman/Desktop/moqui-framework-1.6.1-bin/runtime
	- config file: /Users/ayman/Desktop/moqui-framework-1.6.1-bin/runtime/conf/MoquiDevConf.xml
```

**java -jar moqui-1.6.1.war -load**	
```
	Initializing Moqui ExecutionContextFactoryImpl
	- runtime directory: /Users/ayman/Desktop/moqui-framework-1.6.1-bin/runtime
	- config file: /Users/ayman/Desktop/moqui-framework-1.6.1-bin/runtime/conf/MoquiProductionConf.xml
```

**Comment by jonesde** [comment]
This is how it is expected to behave. See the Run/Deploy document for details:

http://www.moqui.org/framework/docs/RunDeploy.html

The ant and gradle load tasks pass a parameter to use the dev conf file. If you run the WAR file as an executable JAR with java -jar and don't specify a moqui.conf system property (as described in the Run/Deploy document) then it gets the conf file to use from MoquiInit.properties, and there by default it is set to the production conf file.
