### ISSUE TITLE
EntityDataEdit unable to update Enumeration because of multiple lastUpdatedStamp

### ISSUE THREAD

**Issue by donniexyz** [moqui/moqui-framework#274]
Seems its because the entity is related to itself.
/vapps and /apps are impacted.

**To reproduce**
1. Login, 
2. visit this link: https://demo.moqui.org/vapps/tools/Entity/DataEdit/EntityDataEdit?enumId=STT_ERROR&pageIndex=0&selectedEntity=moqui.basic.Enumeration
3. change description, click Update

**This error will pops up**
1. Error updating Enumeration {enumId=STT_ERROR}
2. Error while setting value for field moqui.basic.Enumeration.lastUpdatedStamp: org.moqui.entity.EntityException: Class java.util.ArrayList not allowed for date-time (Timestamp) fields, for field moqui.basic.Enumeration.lastUpdatedStamp
3. Class java.util.ArrayList not allowed for date-time (Timestamp) fields, for field moqui.basic.Enumeration.lastUpdatedStamp

**This is POST data XHR request** https://demo.moqui.org/apps/tools/Entity/DataEdit/EntityDataEdit/update :

```
{
  "screenPathList" : [ "apps", "tools", "Entity", "DataEdit", "EntityDataEdit" ],
  "currentParameters" : {
    "lastUpdatedStamp" : [ "1509605754593", "1509605754593" ],
    "org.apache.catalina.AccessLog.RemoteAddr" : "172.68.144.21",
    "enumId" : "STT_DOJO",
```

Maybe those lastUpdatedStamps are coming from here:
(HTML form)
```
<form name="UpdateEntityValue" id="UpdateEntityValue" novalidate="novalidate"><input type="hidden" name="moquiFormName" value="UpdateEntityValue"> <input type="hidden" name="lastUpdatedStamp" value="1508721148388">
...
<div class="form-group"><label for="UpdateEntityValue_relatedEnumId" class="control-label col-sm-2">Related Enum ID</label> <div class="col-sm-10"><input id="UpdateEntityValue_relatedEnumId" type="text" name="relatedEnumId" value="" size="30" class="form-control"></div></div>
```

**Comment by donniexyz** [comment]
IMO lastUpdatedStamp value should be generated by server to avoid user tampering.

**Comment by jonesde** [comment]
This is caused by the form-single macro now always adding the lastUpdatedStamp if available and is fixed for the Auto Screens and entity edit screen in commit fccf2458.

The lastUpdatedStamp is a special field and is never used to update the database value, it is only used to check against the database value for optimistic lock (ie error on update if something/someone else updated the record since it was loaded so needs to be passed through the form).
