### ISSUE TITLE
Template Error: expression 'sri.sfi' was null or not found WebrootVue.vuet.ftl

### ISSUE THREAD

**Issue by hanyou** [moqui/moqui-framework#276]
currentScreenDef = sri.sfi.getScreenDefinition(currentSubscreensItem.location)
I want to get Screen Definition in the vue.ftl, but display Template Error.

**Comment by jonesde** [comment]
Is this in a screen definition or FTL file that you wrote, or in one of the Moqui project screens/template? What are the steps to reproduce? What is the error in your log (errors in the HTML output are intentionally kept minimal)?

**Comment by jonesde** [comment]
Closing for lack of response, you can reopen if needed.
