### ISSUE TITLE
After login UserFacadeImpl.currentInfo.internalArtifactAuthzCheckList retain dirty information

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#28]
A bug introduced by commit 11ca1d5, After user login `loginAfterAlways` method will call some services, which call `isPermitted` and populate `currentInfo.internalArtifactAuthzCheckList`. Then `pushUserSubject` method will call `setInfo` on `currentInfo` other than create a new `UserInfo`.

Following command can show the result, AppList will not list any apps because `isPermitted == false`.
`curl -u username:password -o - http://localhost:8080/apps`

**Comment by chunlinyao** [comment]
Maybe these collections should be set to null when call `setInfo`.

        Set<String> internalUserGroupIdSet = (Set<String>) null
        // these two are used by ArtifactExecutionFacadeImpl but are maintained here to be cleared when user changes, are based on current user's groups
        EntityList internalArtifactTarpitCheckList = (EntityList) null
        EntityList internalArtifactAuthzCheckList = (EntityList) null

**Comment by jonesde** [comment]
Thank you, this is fixed in commit #b367cf0. I think this didn't happen in my manual tests because the AppList screen rendered after a user was logged in, so the UserInfo was populated from the user in the web session.
