### ISSUE TITLE
owner-form related issue

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-framework#280]
1).when using form-single with the owner-form and extends at the same time, the text-line can not be edit.
2). when using form-single with the owner-form attr, the field using drop-down dynamic-options depends-on is not working. it can't get the value when the depends-on field (within owner form) get changed. while the field and depends-on field with the same form-single, it works fine.

**Comment by jonesde** [comment]
The form-single.@owner-form attribute is a hack requested by a client to handle a particular layout issue. I'm more likely to remove it than resolve every issue that might come up with it. I would recommend not using it.

What is the scenario where you are using it? Why not keep all fields in the same form-single?

**Comment by WillWei1983** [comment]
Well, @owner-form is a very cool function to me. I want to make the layout(or UI interactive?) like the odoo way. we are using this by having a main screen with form-single only for the submit, cancel button,then other main fields with another form-single with @owner-form(in the same xml screen). and the rest of different related fields in the different subscreens(type='tab' ) form-single with @owner-form.  such that when user finishing input the related info, submit the form ,the service can handle the submitting at a time. not one by one form-single to insert the record to the releated entities.

**Comment by jonesde** [comment]
I'm closing this as I have no intention of changing separate form-single forms to behave as one even if owner-form is used. They are rendered as separate forms that don't know anything about each other. You can do some custom layouts with the new field-col-row and field-col elements (along with field-group, etc). 

If you want a really custom form layout or screen layout then don't use XML Forms... they are meant for building lots of forms in larger applications and keeping things consistent and there is no intent (and never will be) to support any arbitrary layout or dynamic behavior you might imagine. If you need those sorts of things, build custom FTL templates (for Vue templates if that is your target, to be client rendered) and then you have full control of the HTML, JavaScript, etc.

If you want a single form split across screens you have an even bigger issue and could only do that using server-side rendering by keeping temporary data in the session or having a service per screen in a series that persists the data along the way (my preferred approach). For a more dynamic UI use something like a custom Vue JS component on your screen so you can more easily build more dynamic screens all rendered in the browser, gathering a bunch of data to send to the server all at once in the background (if that's what you want).

You could submit feature requests if you want more, and maybe someone will pick one up and work on it.
