### ISSUE TITLE
new UI interaction is need

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-framework#281]
I would like simply to show or hide some fields within a form-single and even a containers out of the form-single depends on a drop-down, radio or checkbox.
as the flt template didn't support the onchanged even for radio, checkbox, yet, I need to do it by js, but the html for a field only has a class attr like <div class="form-group">. it has no id attr.

**Comment by jonesde** [comment]
Right now there is an id attribute on the span that wraps the checkbox and radio input elements. You can use that plus the input sub-element in your jQuery selector. You could also write a jQuery selected that doesn't depend on the ID at all using the form and input names. I'd recommend reading up on radio and checkbox selectors as they are a special situation where it is common for multiples to have the same name and a more specific selector is often needed.
