### ISSUE TITLE
Is the business integrity of moqui?Can it be used in production

### ISSUE THREAD

**Issue by mylovetop** [moqui/moqui-framework#283]
hi
Is the business integrity of moqui?Can it be used in production。 
The tables of the moqui database are not many in contrast to ofbiz
thank you

**Comment by jonesde** [comment]
This would be a better topic for the LinkedIn forum.

For a brief answer: Moqui Framework has been used in production systems around the world for a few years now, and the first productions systems using Mantle UDM, USL, SimpleScreens, and PopCommerce when live earlier this year.
