### ISSUE TITLE
Why implement the EntityIterator but not just return valueList.iterator() in EntityListImpl.java

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-framework#286]
Hi
after using the entity-find and then get the list object, then I try to iterate the list object to remove some item according to some conditions. but the output is not the expected. the loop will miss when remove() happens. 
I copy the value in the list to an ArrayList, and it works fine, Then I trace the entity-find, I found the list.iterator() it not the ArrayList's iterator(). the EntityListImpl's iterator() return an new EntityIterator(). which that hasNext() using the valueList.size() to compare the valueList.size() is returning the dynamic length of the valueList. so this is the root cause of the 'not expected result'
Then my question is that why the EntityListImpl has to implement it byself, any design purpose behind it?

**Comment by jonesde** [comment]
Please see the new Issue and Pull Request Guide:

https://github.com/moqui/moqui-framework/wiki/Issue-and-Pull-Request-Guide

The main reasons that EntityListImpl returns a custom iterator is for convenience with type safety, to enforce immutable lists (from cache), and in general avoid exposing the internal ArrayList (which was part of the optimization effort a while back, handling directly by indexes and such, keeping the iterator much lighter and faster).

I couldn't follow the error situation you described. As mentioned in the new issue guide specific steps to reproduce are helpful, in this case actual code or psuedo code at least would help.

**Comment by WillWei1983** [comment]
Sorry for the inconvenience.
`<entity-find-one entity-name="mantle.party.PartyRelationship" value-field="orgInfo">
                <field-map field-name="fromPartyId" from="orgId"/>
</entity-find-one>
<entity-find entity-name="mantle.party.PartyRelationship" list="internalOrgList2">
                   <econdition field-name="lftPoint" from="orgInfo.lftPoint" operator="greater"/>
                    <econdition field-name="rgtPoint" from="orgInfo.rgtPoint" operator="less"/>
                    <order-by field-name="lftPoint"/>
</entity-find>
`
<br/>
Below is the code I am using to iterate the list
<script><![CDATA[ <br/>
                    Iterator<EntityValue> it = internalOrgList2.iterator()  <br/>
                    List<EntityValue> toRemoveList = new ArrayList<EntityValue>();  <br/>
                    while (it.hasNext()) { <br/>
                        EntityValue subOrg = (EntityValue)it.next() <br/>
                        //in case of an OrgInternal,save it to a list for later use, then remove it <br/>
                        if(("OrgInternal").equals(subOrg.fromRoleTypeId)){ <br/>
                            toRemoveList.add(subOrg) <br/>
                            it.remove() <br/>
                        } <br/>
                        //check if the org is sub node of the OrgInternal, if Y, then remove it <br/>
                        for(EntityValue internalOrg in toRemoveList){ <br/>
                            if(subOrg.lftPoint > internalOrg.lftPoint && subOrg.rgtPoint < internalOrg.rgtPoint){ <br/>
                                it.remove() <br/>
                            } <br/>
                        } <br/>
                    } <br/>
                ]]></script> <br/>
in my case the original value of internalOrgList2 have 3 records, and all of them should be removed.
but the 2nd record is still in internalOrgList2  after the while loop finished.
and when I test the 3 records with an ArrayList, the outcome is expected.

----------below is my investigation-----------
As the method hasNext() in EntityListImpl --> EntityIterator is as flows
{ return (curIndex + 1) < valueList.size(); }
the valueList.size() return the 'current length of the array' so when a record is removed, the size is minus 1 then lead to the loop minus related times

**Comment by jonesde** [comment]
The changes in commit c7e83e66 should resolve this.
