### ISSUE TITLE
After pull the latest framework, there is error when build

### ISSUE THREAD

**Issue by hexd-moshi** [moqui/moqui-framework#288]
Error message is No property classesDirs in file framework/build.gradle , line 192 and 207.
After change classesDirs  to classesDir, it is OK

**Comment by jonesde** [comment]
Which version of Gradle are you using? If it is before 4.0 you'll need to update.

**Comment by hexd-moshi** [comment]
Thanks for your advice, after update Gradle to the latest release, it is OK.
