### ISSUE TITLE
Aggregations do not work with sub-select=true

### ISSUE THREAD

**Issue by diegonc** [moqui/moqui-framework#291]
I've found that, in a `view-entity` with a `member-entity` set to be handled as a sub select, the aggregation functions will not work appropriately. The "GROUP BY" clause is not generated at all.

Test case: [issue291.tar.gz](https://github.com/moqui/moqui-framework/files/1543077/issue291.tar.gz)

For instance, in the attached example, the service `issue291.Services.countBySalesMan#Sale` will call the following SQL query:

```sql
SELECT
	SALES.SALES_MAN_ID,
	COUNT( SALES.SALE_ID ),
	SUM( SALES.PRODUCT_PRICE )
FROM
	(
		SELECT
			SALESMAN.SALES_MAN_ID AS SALES_MAN_ID,
			SALES.ID AS SALE_ID,
			PROD.PRICE AS PRODUCT_PRICE
		FROM
			SALE SALES
		INNER JOIN SALE_SALES_MAN SALESMAN ON
			SALES.ID = SALESMAN.SALE_ID
		INNER JOIN PRODUCT PROD ON
			SALES.PRODUCT_ID = PROD.ID
	) SALES
```

So, the select fields are generated correctly but as no group by is produced the meaning of the query is completely different.

Digging in the source code I found the group by is generated in `EntityFindBuilder.java` but only for those entities whose `entityInfo` has the `hasFunctionAlias` flag on. Then, looking at `EntityJavaUtil.java`, I realised this property was never set when the fields with aggregations came from a sub-select.

I tried the following patch:

```diff
diff --git a/framework/src/main/groovy/org/moqui/impl/entity/EntityJavaUtil.java b/framework/src/main/groovy/org/moqui/impl/entity/EntityJavaUtil.java
index 1dc7d18b..2a052bf2 100644
--- a/framework/src/main/groovy/org/moqui/impl/entity/EntityJavaUtil.java
+++ b/framework/src/main/groovy/org/moqui/impl/entity/EntityJavaUtil.java
@@ -313,9 +313,7 @@ public class EntityJavaUtil {
                 if ("true".equals(fi.enableAuditLog) || "update".equals(fi.enableAuditLog)) needsAuditLogTemp = true;
                 if ("true".equals(fi.fieldNode.attribute("encrypt"))) needsEncryptTemp = true;
                 if (isView && fi.hasAggregateFunction) {
-                    MNode memberEntity = fi.memberEntityNode;
-                    if (memberEntity == null || !"true".equals(memberEntity.attribute("sub-select")))
-                        hasFunctionAliasTemp = true;
+                    hasFunctionAliasTemp = true;
                 }
                 String defaultStr = fi.fieldNode.attribute("default");
                 if (defaultStr != null && !defaultStr.isEmpty()) {
```

and the correct SQL query was generated.

```sql
SELECT
	SALES.SALES_MAN_ID,
	COUNT( SALES.SALE_ID ),
	SUM( SALES.PRODUCT_PRICE )
FROM
	(
		SELECT
			SALESMAN.SALES_MAN_ID AS SALES_MAN_ID,
			SALES.ID AS SALE_ID,
			PROD.PRICE AS PRODUCT_PRICE
		FROM
			SALE SALES
		INNER JOIN SALE_SALES_MAN SALESMAN ON
			SALES.ID = SALESMAN.SALE_ID
		INNER JOIN PRODUCT PROD ON
			SALES.PRODUCT_ID = PROD.ID
	) SALES
GROUP BY
	SALES.SALES_MAN_ID
```

But I'm not sure whether it has other side-effects or not. Could you have a look?
Thanks

**Comment by jonesde** [comment]
The example you included may be too artificial to adequately comment on, ie it doesn't make sense to have a view-entity with a single member-entity that is a sub-select (SalesManTotals) when you could just put the functions on the corresponding SaleSalesManProduct view-entity aliases. You can have functions on both the sub-select and the main select, in some cases you have to tell it that it should be treated as an aggregate function (using the attribute for that, was added to handle mixes between aggregate and non-aggregate functions).

The change you propose will break existing functionality which supports one mode for sub-select members that are plain entities and another for sub-select members that are view-entities.

**Comment by diegonc** [comment]
They are artificial but based on use cases we are working on. Currently we are using something similar to `SaleSalesManProduct` to populate a table with details of operations and a DynamicEntityView similar to `SalesManTotals` to get sums of those operations over several periods of time.

I cannot just merge them. And not using a single member-entity would mean to duplicate the actual implementation of `SaleSalesManProduct`.

BTW, this is not a sub-select because I want to but because otherwise I get the following exception (which is an issue that I couldn't manage to submit yet):

```
Caused by: org.moqui.entity.EntityException: Could not find field price in entity issues.t291.SaleSalesManProduct
	at org.moqui.impl.entity.EntityFindBuilder.makeSqlFromClause(EntityFindBuilder.java:159) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindBuilder.makeSqlViewTableName(EntityFindBuilder.java:365) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindBuilder.makeSqlFromClause(EntityFindBuilder.java:330) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindBuilder.makeSqlFromClause(EntityFindBuilder.java:99) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindImpl.iteratorExtended(EntityFindImpl.java:118) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindBase.listInternal(EntityFindBase.groovy:1063) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	... 24 more
```

**Comment by jonesde** [comment]
Various improvements to this have been done over the last year. If this is still an issue please file a request on moqui.org to track it, closing out here to clean up old issues and ultimately disable issues for the moqui-framework repository just like all other moqui repos. For details see:

https://www.moqui.org/m/docs/moqui/Community+Guide
