### ISSUE TITLE
date-filter looks up the fields in the wrong entity

### ISSUE THREAD

**Issue by diegonc** [moqui/moqui-framework#293]
When a `<date-filter />` is used as a join condition (i.e. in an `entity-condition` whose parent is `member-entity`) Moqui will try to find the from and thru fields in the definition of the enclosing `view-entity`.

Test case: [issue293.tar.gz](https://github.com/moqui/moqui-framework/files/1543940/issue293.tar.gz)

The test case has the following example:

```xml
<view-entity entity-name="SaleProduct" package="issues.t293">
    <member-entity entity-alias="SALE" entity-name="issues.t293.Sale" />
    <member-entity entity-alias="PRODPRICE" entity-name="issues.t293.ProductPrice"
            join-from-alias="SALE">
        <key-map field-name="productId" related-field-name="productId" />
        <entity-condition>
            <date-filter />
        </entity-condition>
    </member-entity>

    <alias name="soldAt" entity-alias="SALE" field="soldAt" />
    <alias name="productId" entity-alias="SALE" field="productId" />
    <alias name="productPrice" entity-alias="PRODPRICE" field="price" />

    <!-- XXX export date fields to workaround date-filter issue -->
    <!-- <alias name="fromDate" entity-alias="PRODPRICE" field="fromDate" /> -->
    <!-- <alias name="thruDate" entity-alias="PRODPRICE" field="thruDate" /> -->
</view-entity>
```
This should list all the sales with the current price of the sold products. However, the exception below is triggered instead.

```
Caused by: org.moqui.entity.EntityException: Could not find field fromDate in entity issues.t293.SaleProduct
	at org.moqui.impl.entity.condition.FieldValueCondition.makeSqlWhere(FieldValueCondition.java:70) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.condition.ListCondition.makeSqlWhere(ListCondition.java:86) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.condition.ListCondition.makeSqlWhere(ListCondition.java:86) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.condition.DateCondition.makeSqlWhere(DateCondition.groovy:41) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindBuilder.makeSqlFromClause(EntityFindBuilder.java:308) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindBuilder.makeSqlFromClause(EntityFindBuilder.java:99) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindImpl.iteratorExtended(EntityFindImpl.java:118) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	at org.moqui.impl.entity.EntityFindBase.listInternal(EntityFindBase.groovy:1063) ~[moqui-framework-2.1.1-rc1.jar:2.1.1-rc1]
	... 24 more
```

I don't have a patch for this issue. We were happy with the workaround shown by the comments in the snippet above. (i.e. alias the date fields you use in the view-entity definition)

--
BTW, if you don't mind a side question: how should I change this date-filter usage such that instead of comparing to `now` it would compare the dates to another field (for instance, `SALE.soldAt`)? Thanks

**Comment by jonesde** [comment]
View-entity fields must be aliased to be used in conditions, selected, ordered by, etc. There never will be a work around for this because it is a fundamental part of how entity definitions and by extension view-entity definitions are designed.

The date-filter only creates conditions for comparing from/thru date fields (you can specify different names using attributes) to a compare date that is between the dates. It is a convenience feature for common usage, not the only way to do this as you can define econditions as needed for other date/time field conditions.

**Comment by diegonc** [comment]
`fromDate` and `thruDate` are obviously aliased in `issues.t293.ProductPrice`. The `date-filter` is just looking in the wrong entity definition.

Look at the query after the workaround:

```sql
SELECT
	SALE.SOLD_AT,
	SALE.PRODUCT_ID,
	PRODPRICE.PRICE,
	PRODPRICE.FROM_DATE,
	PRODPRICE.THRU_DATE
FROM
	SALE SALE
INNER JOIN PRODUCT_PRICE PRODPRICE ON
	SALE.PRODUCT_ID = PRODPRICE.PRODUCT_ID
	AND(
		(
			PRODPRICE.FROM_DATE IS NULL
			OR PRODPRICE.FROM_DATE <=?
		)
		AND(
			PRODPRICE.THRU_DATE IS NULL
			OR PRODPRICE.THRU_DATE >?
		)
	)
```

The conditions are OK, but I'm forced to have those dates selected unnecessarily. They might not even make sense to have them as fields of the view entity being defined. It's just some internal join condition.

**Comment by jonesde** [comment]
Fields will only be selected if they are in the list of fields to select, or all will be selected if no fields to select are specified, so specify just the fields you want selected.

BTW, one of your other patches looked like it might break this behavior.

In general I'd recommend going back to the stock framework without any of your changes and follow patterns used in existing view-entity definitions in mantle and such, there are a number of complex ones that are tested across various databases and working fine.

A lot of this is newer functionality (all the sub-select stuff and some of the more advanced options) and there are lots of ways you can mess up entity definitions. I don't have even close to the time to review all of what you are trying to do and fix things for you, hence the recommendation above.

**Comment by diegonc** [comment]
> Fields will only be selected if they are in the list of fields to select, or all will be selected if no fields to select are specified, so specify just the fields you want selected.

Sure, that's way I settled for the extra alias and didn't bother to look at the code. However, it feels weird to have to put things in a view-entity that conceptually don't belong there.

> BTW, one of your other patches looked like it might break this behavior.
Probably, I've been working in a rush this days :stuck_out_tongue_closed_eyes: Now that I have some free time I'll try to find out how to run the tests and look for regressions.

> I don't have even close to the time to review all of what you are trying to do and fix things for you, hence the recommendation above.
No problem. I just thought it was useful to post the issues that looked like bugs.
