### ISSUE TITLE
Drop down list order by?

### ISSUE THREAD

**Issue by okroener** [moqui/moqui-framework#301]
I have just checked the XSD for the <drop-down> element, but dit no find a order by clause.

The reason for that is, that the list should be ordered by a specific field of the entity, is that option missing or did I not find it?

By the way I work with Moqui 2.1.1RC ...

Thx

**Comment by jonesde** [comment]
Going forward please file requests for support on the new HiveMind instance on moqui.org. For more information about community infrastructure see:

https://www.moqui.org/docs/moqui/Community+Guide

In the near future issues on GitHub will be disabled altogether.

The order of options should be specified in the sub-elements to the drop-down element. There are many examples of this for entity-options, and for list-options you would do this in the data prep code.
