### ISSUE TITLE
Improve GeoTypeAndAssocFromDetail view entity 

### ISSUE THREAD

**Issue by gagaboy** [moqui/moqui-framework#303]
In the view entity moqui.basic.GeoTypeAndAssocFromDetail,the toGeoId field is the same as geoId field .There need the fromGeoId field to relate the from associated geoId.So in this view entity definition these code 
`
        <alias-all entity-alias="GEOA"/>
        <alias-all entity-alias="GEOFR" prefix="from"><exclude field="geoId"/></alias-all>
    </view-entity>
`
should be 
`
<alias-all entity-alias="GEOA"><exclude field="toGeoId"/></alias-all>
        <alias-all entity-alias="GEOFR" prefix="from"/>
    </view-entity>
`

**Comment by jonesde** [comment]
I'm fine with adding the fromGeoId alias, but don't like the idea of removing the existing toGeoId alias (even if it is the same via join condition as the geoId field, no point in breaking backwards compatibility).

This is done in commit 8d828a43.

For future reference: please don't create issues on GitHub. They are not yet disabled to avoid losing older issues, but all requests should now go in HiveMind on moqui.org. Please see:

https://www.moqui.org/m/docs/moqui/Community+Guide
