### ISSUE TITLE
How to use jsf on Moqui

### ISSUE THREAD

**Issue by rongnguyen** [moqui/moqui-framework#313]
Hi,

I would like to use JSF on Moqui. Please suggest me how to implement it.

Thank for great framework!

**Comment by jonesde** [comment]
This is more of a how-to question than an issue. A better place is on StackOverflow or a request for support on moqui.org using HiveMind. For a discussion that reaches a wider audience the best place is still the LinkedIn forum. For more information please read through the Community Infrastructure Guide:

https://www.moqui.org/m/docs/moqui/Community+Guide
