### ISSUE TITLE
Client render screen with Vue dose not work for dynamic-dialog

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/moqui-framework#317]
For example,                     

`<dynamic-dialog id="Test" button-text="View Dynamic Example Items" transition="//example/DynamicExampleItems" />`

Which does not work.

**Comment by jonesde** [comment]
That looks like an invalid transition. There are lots of examples of this working fine, including on the EditParty screen in SimpleScreens and many others.

**Comment by zhangwei1979** [comment]
Yes, dynamic-dialog works but vuet mode dose not work. See attached screen 
<img width="817" alt="qq20180503-165032 2x" src="https://user-images.githubusercontent.com/11864498/39567625-3405bce8-4ef2-11e8-9b99-89f06e734b82.png">
shot

**Comment by jonesde** [comment]
I see, that's correct, it is not currently supported. This should be possible, the loader for dynamic-dialog and dynamic-container would have to be changed to support the .js + .vuet (optional) loading in WebrootVue.js.

**Comment by zhangwei1979** [comment]
I am finding a way to implement a Lookup Screen in OFBiz, see https://www.moqui.org/vapps/my/User/Request/EditRequest?requestId=100357

**Comment by jonesde** [comment]
As you probably know in general all issues and new features requests should go in HiveMind on moqui.org, so closing this issue as there is already a related request there.

I added some notes to that request. Basically if you want something like this in your application you can build a custom screen (server rendered FTL or client rendered Vue JS template) with a dialog that interacts with the screen as you wish. As a hint, don't use dynamic-dialog as it is not designed to populate something in the parent screen based on something clicked, you have to add custom JavaScript to do that.
