### ISSUE TITLE
Service params not showing in ServiceRun tool

### ISSUE THREAD

**Issue by akhiar** [moqui/moqui-framework#32]
If a service with verb "update" has in-params with "required" attribute set to true, that particular param will not shown in ServiceRun tool screen. It is not a bug as it is written explicitly [here](https://github.com/moqui/moqui-framework/blob/e3742b158aefe54895b87a2d85f621d13c280f8c/framework/src/main/groovy/org/moqui/impl/screen/ScreenForm.groovy#L549), but I don't understand why. To make that required param showing, I have to rename the service's verb to something else.

```java
    void addAutoServiceField(ServiceDefinition sd, EntityDefinition nounEd, MNode parameterNode, String fieldType,
                             String serviceVerb, MNode newFieldNode, MNode subFieldNode, MNode baseFormNode) {

...

                if (parameterNode.attribute("required") == "true" && serviceVerb.startsWith("update")) {
                    subFieldNode.append("hidden", null)
                } else {

...

```

**Comment by jonesde** [comment]
This is changed (fixed) in commit #ff6aaa3.

The original idea, IIRC, was to handle PK fields but overall it really doesn't make sense. If PK fields should be handled different the form using the auto fields tags (for service or entity) should handle them separately, just as the AutoEditMaster screen does.
