### ISSUE TITLE
Locate and identify website visitors by IP address.

### ISSUE THREAD

**Issue by vigdin** [moqui/moqui-framework#324]
https://github.com/moqui/moqui-framework/blob/c0f656b92d1392d3e64bc1e916a08ee91b41450f/framework/service/org/moqui/impl/ServerServices.xml#L55

Can you please provide an alternative for this.

**Comment by jonesde** [comment]
In the latest code this service is disabled with an unconditional return at the beginning of the get#VisitClientIpData service. Unless a free and open alternative geo IP service is found this won't be replaced and will turn into an interface that a custom geo IP lookup service can plugin to (can be done now by putting a service with the same path and name in your own component), that might be the only option going forward, each company using their own paid account for geo IP lookup... if you care enough about it to pay for a service and do the integration.

**Comment by jonesde** [comment]
The freegeoip service is gone and I'm not aware of any replacement. Closing this as something that has no good solution. If you want to continue with this please file a request on moqui.org as described in the Community Infrastructure Guide as the resource to use for things like this:

https://www.moqui.org/m/docs/moqui/Community+Guide
