### ISSUE TITLE
Occasional exception after login

### ISSUE THREAD

**Issue by aabiabdallah** [moqui/moqui-framework#33]
Occasionally, if I keep the login page open for a long time then I login using the John Doe button an exception is thrown:

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 java.util.LinkedList.checkElementIndex(LinkedList.java:555) java.util.LinkedList.get(LinkedList.java:476) org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:370) org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:166) org.moqui.impl.webapp.MoquiServlet.doScreenRequest(MoquiServlet.groovy:73) org.moqui.impl.webapp.MoquiServlet.doPost(MoquiServlet.groovy:39) javax.servlet.http.HttpServlet.service(HttpServlet.java:648) javax.servlet.http.HttpServlet.service(HttpServlet.java:729) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)`

The only way forward is manually updating the URL to point to the app list.

**Comment by akhiar** [comment]
Should have been fixed in pull request #3. Please update your repo.

**Comment by jonesde** [comment]
Let me know if you run into this again after updating. I'll leave it open for now.

**Comment by jonesde** [comment]
This seems to be an older issue that was temporarily in the master branch (trunk) code and has been fixed. Closing the issue.
