### ISSUE TITLE
Does Moqui have any plan for implementing full udm like ofbiz ?

### ISSUE THREAD

**Issue by amirmf** [moqui/moqui-framework#333]
for exp ...there is no implementation for HR or Manufacturing or ... !
or any tools that convert the ofbiz entity to moqui entities

**Comment by jonesde** [comment]
Here is the data model from Mantle Business Artifacts, a part of the Moqui Ecosystem, and yes there are both entities and some logic (in mantle-usl) already for HR and Manufacturing:

https://github.com/moqui/mantle-udm

I wouldn't recommend converting OFBiz entities to Moqui, you'd have to build all the logic on top of that and that is a much larger effort. The Mantle UDM model is also significantly cleaned up and refactored versus the OFBiz data model. For data migration from OFBiz to Moqui, which is also helpful to see some of the similarities and differences in the models, see:

https://github.com/jonesde/OFBizToMantle

For future reference this is only for issues, the LinkedIn Forum or mailing lists would be a more appropriate place to discuss this:

https://www.moqui.org/m/docs/moqui/Community+Guide
