### ISSUE TITLE
Restricting Single User Login in Multiple Machine until log out and session expired.

### ISSUE THREAD

**Issue by vigdin** [moqui/moqui-framework#334]
A user (say User1) is having two machine (say  A and B).Consider the User1 is logged in machine A and if he tries to login in machine B with the same user (User1), we  need to restrict him until he "logged-out or session expired" in Machine A.
In UserAccount table, we saw "hasLogOut" field. If we logged in we are putting entry as 'N'.But while logged-out or session expires, we are not seeing any changes. Can you give us some suggestion to handle this ?

**Comment by jonesde** [comment]
Issues on GitHub are only open to retain some older issues. Please file new feature requests like this on moqui.org, see:

https://www.moqui.org/m/docs/moqui/Community+Guide#issues-and-other-requests
