### ISSUE TITLE
service definition   xml file 

### ISSUE THREAD

**Issue by sergei-iliev** [moqui/moqui-framework#342]
Hi,
Is it possible to define an <include> tag in service's schema xml file in order to allow service definition nesting?
Struts has such a tag  =>“include file” feature to include multiple Struts configuration files into a single unit.
For reasons i would not like to go into , we are using a single service definition file and would like to have a single entry point (URL path) to services.
Having such include file feature will allow us to continue in this direction aka having a single URL services entry point, by splitting the big services' xml file into smaller manageable xml files. 
Regards

**Comment by jonesde** [comment]
Yes, this could be done. I've considered something like this recently to help reorganize the growing services, and number of logically grouped services, in the service XML files in mantle-usl. Right now you can define a service that simply calls another service but that is a bit less efficient than 'aliasing' a service in another file and using the exact service definition and implementation defined elsewhere.

This is not a high priority being part of a clean up effort that is really just a nice to have, but on the other hand would not require a great deal of time to do.

**Comment by jonesde** [comment]
I plan to do this sooner or later but trying to close out all issues here as they should be filed as requests on moqui.org if you want a place to track this new feature request. Please see the Community Infrastructure Guide for more details:

https://www.moqui.org/m/docs/moqui/Community+Guide
