### ISSUE TITLE
Is a warning necessary when deleting old promotions (FindPromotion.xml)?

### ISSUE THREAD

**Issue by fizzyduck** [moqui/moqui-framework#346]
Firstly, apologies for not raising this on the SimpleScreens repo - it doesn't have an issue tracker.

I noticed a comment in [FindPromotion.xml](https://github.com/moqui/SimpleScreens/blob/b9fe1123ede76124bd0ed94614ff4627b44dce56/screen/SimpleScreens/ProductStore/Promotion/FindPromotion.xml#L98) which suggests that deletion of promotions hasn't been implemented due to the need for a service which can see if a Promotion has been previously used.

Is a link to the promotion that was applied actually stored anywhere? I notice when looking at a created Order that the detail of the Promotion has been applied as it was set up at the time and the textual details are recorded in the Order, but a link to the Promotion is not (which seems correct to me).

Additionally, given it is possible to retrospectively change the details of a Promotion after it has been applied to an Order and this will only affect new Orders made after that change, then we should consider that a Promotion is something that is applied as a "rubber stamp". Its details should be copied in to the Order (the text and formula that were present in the Promotion at the time) and then no longer be associated with the Promotion object.

I am quite new to the architecture so may well have missed something obvious - apologies if that is the case.

**Comment by jonesde** [comment]
For more information on community resources available please see the Community Infrastructure Guide:

https://www.moqui.org/m/docs/moqui/Community+Guide

This is more of a discussion than an issue or request to track, I'd recommend using the Moqui Applications mailing list: moqui-applications@googlegroups.com

If this turns into a request for a new feature that should be filed in HiveMind on moqui.org as described in the infra guide above.
