### ISSUE TITLE
"Update" button in SimpleScreens/FindPromotion.xml fails to append "productStoreId" parameter

### ISSUE THREAD

**Issue by fizzyduck** [moqui/moqui-framework#347]
Version: 2.1.1

Steps to reproduce:

0. Use the OOTB Moqui demo.
1. Navigate to: http://localhost:8080/apps/PopcAdmin/ProductStore/Promotion/FindPromotion?productStoreId=POPC_DEFAULT
2. Press "Update"

**Expected result:**
List of promotions is saved and refreshed.
**Actual result:**
Error message "Required parameter missing (productStoreId) Required parameter missing (productStoreId)" appears.
URL contains http://localhost:8080/apps/PopcAdmin/ProductStore/Promotion/FindPromotion

**Comment by jonesde** [comment]
I mentioned this on the other issue you filed, the community infra guide may be helpful:

https://www.moqui.org/m/docs/moqui/Community+Guide

This should be filed as a request for bug fix on moqui.org.
