### ISSUE TITLE
Screen history list "context" as a parameter key.

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#35]
Screen history show something like this.

    Tools - Dashboard (========== Start stack level 0
    ========== End stack level 0
    ========== Start stack level 1
    ========== End stack level 1
    ========== Start combined Map
    ==>[context]:<Instance of ContextStack, not printing to avoid infinite recursion>
    ========== End combined Map
    )
                    
I think this is because web.requestParameters use ContextStack to combine all parameter maps.

**Comment by jonesde** [comment]
This is fixed in commit #73f50c1, details in commit message.
