### ISSUE TITLE
NOT AN ISSUE: Using api_key with JSON-RPC

### ISSUE THREAD

**Issue by domiko** [moqui/moqui-framework#351]
Hi.

I know the support exists with REST calls but are api_keys supported with JSON-RPC calls?
I've tried passing the api_key through URL, HTTP Header and 'params' to no avail.
I've checked the code as well and couldn't find a place where this kind of authc could happen.

I'm currently, while developing, passing user/password in basic authc on every request. But I doubt login in on every request is the way to go (and I've seen issues when the volume of requests increases).

I guess some people will suggest to go the REST route but I feel/think that JSON-RPC is a far better option (that I could explain in other messages if needed).

Kudos of a great platform.

Regards,
Dom

**Comment by jonesde** [comment]
The 'api_key' header is checked in UserFacadeImpl for all requests that go through the MoquiServlet or otherwise have a WebFacade in place. In other words yes, JSON RPC calls through the default /rpc/json screen transition (which handles those requests) would look at the api_key header just like through /rest/s1 or whatever.

What did you mean by not an issue? Do you have a test case where this failed or did it work fine and this can be closed?

**Comment by domiko** [comment]
Hi David.

I meant, this issue is not really an issue but more a question.

I don't have a test case as of now but what I do is:
Obtain an apiKey by calling the following in a custom service.
`<script>ec.user.loginUser(username, password)</script>`

I use this apiKey to call another custom service via Postman by placing it as a header attribute with the name 'api_key' (I also tried 'x-api-key' and 'apiKey').
i.e.
`api_key:oKPC7SXh7UHKoujF5xemKHiwaEUgYA57x-5K5WAe`

I get the following error:
`Error 401 Authentication Required
Problem accessing /rpc/json
Reason: Session token required (in moquiSessionToken) for URL http://localhost:8080/rpc/json`

I'll investigate further now that I have your confirmation that it is supported.
Many Thanks.

**Comment by aabiabdallah** [comment]
Hello,

The error you're getting is related to the session token and not the API key. Moqui requires the moquiSessionToken header to be available in all non-GET requests. 

In case you don't want this behaviour you can disable the session token requirement by setting the require-session-token attribute to false in your webapp config. See the MoquiDefaultConf.xml file for more details.

**Comment by domiko** [comment]
Hi Ayman.

I followed your instructions and it worked like a charm.

Many thanks.

**Comment by b-thebest** [comment]
Hello @aabiabdallah ,
I followed your instructions and changed require-session-token to false in "MoquiDefaultConf.xml" file. I tried calling POST method but its showing error:

```
{
  "servlet": "MoquiServlet",
  "message": "Session token required (in moquiSessionToken) for URL http://localhost:8080/rest/s1/Example/examples/create",
  "url": "/rest/s1/Example/examples/create",
  "status": "401"
}
```

Could you please tell me what should I do?

**Comment by aabiabdallah** [comment]
Hi,

Please check/share the MoquiActualConf.xml file located in runtime/log,
this file will shows the configuration Moqui is using after merging the
MoquiDefaultConf.xml and the config you used for Moqui runtime.

-- 
Regards,
Ayman Abi Abdallah
