### ISSUE TITLE
unable to translate top level menu

### ISSUE THREAD

**Issue by pythys** [moqui/moqui-framework#368]
Hello, I'm not sure if this is a misunderstanding from our side, but it seems like we cannot get the top level component to be translated. More specifically we apply the following:

```xml
<moqui-conf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://moqui.org/xsd/moqui-conf-2.1.xsd">
    <screen-facade>
        <screen location="component://webroot/screen/webroot/apps.xml">
            <subscreens-item name="MySystem"
                    location="component://sparts-workflow/screen/MySystem.xml"
                    menu-index="1"
                    menu-title="${ec.l10n.localize('MySystem')}"/>
        </screen>
    </screen-facade>
</moqui-conf>
```

Then we start to introduce screens underneath. Now the button for the main menu is translated (the title) however, when navigating to the subscreens, the title remains untranslated.

If we try to use something like `default-menu-title="${ec.l10n.localize('Product')}"` then the system will simply not evaluate it and print it as is.

I attach a screenshot for clarification purposes.

![2019-07-10-23:18:50-screenshot-Selection](https://user-images.githubusercontent.com/13056493/61001903-276f2600-a369-11e9-971d-0dfbeaaf334e.png)

![2019-07-10-23:23:45-screenshot-Selection](https://user-images.githubusercontent.com/13056493/61002252-d449a300-a369-11e9-81ba-801db7d757b9.png)

**Comment by dixitdeepak** [comment]
Hi Taher, 

You can directly use the menu-tile without l10 facade, ScreenRenderImpl class take care of its localization.

**Comment by pythys** [comment]
Hi Deepak. Good to know you're here :)

Well, I removed all menu translations and menu title settings everywhere. I still get this weird behavior of some of the menus translating and others not so. I'm not sure if I'm clashing with other namespaces or something.

Attached is another screenshot to showcase the problem.
![2019-07-11-14:33:58-screenshot-Selection](https://user-images.githubusercontent.com/13056493/61047834-0f3eeb80-a3e9-11e9-925c-2ea2fd2bf9ff.png)

**Comment by dixitdeepak** [comment]
Thanks Taher, Welcome to Moqui :)

Please check moqui.basic.LocalizedMessage entity record for your locale. If you created LocalizedMessage for specific locale it should work.

**Comment by pythys** [comment]
Hi Deepak,

Yeah I'm aware of the entity, and got it loaded. Still this weird inconsistent behavior is happening somewhere else. Perhaps I've made a mistake, but not one that I'm able to spot so far. Here is the localization data for example:

```xml
<entity-facade-xml type="seed">
    <moqui.basic.LocalizedMessage original="Applications" locale="default" localized="Applications"/>
    <moqui.basic.LocalizedMessage original="Applications" locale="ar" localized="التطبيقات"/>
    <moqui.basic.LocalizedMessage original="AppList" locale="default" localized="App List"/>
    <moqui.basic.LocalizedMessage original="AppList" locale="ar" localized="قائمة التطبيقات"/>
    <moqui.basic.LocalizedMessage original="Tools" locale="default" localized="Tools"/>
    <moqui.basic.LocalizedMessage original="Tools" locale="ar" localized="الأدوات"/>
    <moqui.basic.LocalizedMessage original="System" locale="default" localized="System"/>
    <moqui.basic.LocalizedMessage original="System" locale="ar" localized="النظام"/>
    <moqui.basic.LocalizedMessage original="My Account" locale="default" localized="My Account"/>
    <moqui.basic.LocalizedMessage original="My Account" locale="ar" localized="حسابي"/>
    <moqui.basic.LocalizedMessage original="SpartsSystem" locale="default" localized="Sparts System"/>
    <moqui.basic.LocalizedMessage original="SpartsSystem" locale="ar" localized="نظام سبارتس"/>
    <moqui.basic.LocalizedMessage original="Dashboard" locale="default" localized="Dashboard"/>
    <moqui.basic.LocalizedMessage original="Dashboard" locale="ar" localized="لوحة القيادة"/>
    <moqui.basic.LocalizedMessage original="Product" locale="default" localized="Product"/>
    <moqui.basic.LocalizedMessage original="Product" locale="ar" localized="منتج"/>
    <moqui.basic.LocalizedMessage original="Order" locale="default" localized="Order"/>
    <moqui.basic.LocalizedMessage original="Order" locale="ar" localized="أمر"/>
    <moqui.basic.LocalizedMessage original="Request" locale="default" localized="Request"/>
    <moqui.basic.LocalizedMessage original="Request" locale="ar" localized="طلب"/>
    <moqui.basic.LocalizedMessage original="Vehicle" locale="default" localized="Vehicle"/>
    <moqui.basic.LocalizedMessage original="Vehicle" locale="ar" localized="مركبة"/>
    <moqui.basic.LocalizedMessage original="FindRequest" locale="default" localized="Find Request"/>
    <moqui.basic.LocalizedMessage original="FindRequest" locale="ar" localized="بحث عن طلب"/>
    <moqui.basic.LocalizedMessage original="NewDirectRequest" locale="default" localized="New Direct Request"/>
    <moqui.basic.LocalizedMessage original="NewDirectRequest" locale="ar" localized="طلب مباشر جديد"/>
    <moqui.basic.LocalizedMessage original="NewInsuredRequest" locale="default" localized="New Insured Request"/>
    <moqui.basic.LocalizedMessage original="NewInsuredRequest" locale="ar" localized="طلب تأميني جديد"/>
    <moqui.basic.LocalizedMessage original="NewSupplierRequest" locale="default" localized="New Supplier Request"/>
    <moqui.basic.LocalizedMessage original="NewSupplierRequest" locale="ar" localized="طلب مورد جديد"/>
</entity-facade-xml>
```

**Comment by pythys** [comment]
I think I figured out the reason for my problems. The system defaults to menu expanded name, not screen name. Thus I have to include spaces in the LocalizedMessage entity. That was a bit confusing at first but now I think I got it right.

Thank you for all the help. I'm closing this ticket now.
