### ISSUE TITLE
About load data with my component

### ISSUE THREAD

**Issue by liaosf** [moqui/moqui-framework#375]
I created my component and write seed-data in data directory:
1、BasicEnumData.xml
`<moqui.basic.Enumeration description="Unified Social Credit Code" enumId="PtidUSCCofChina" enumTypeId="PartyIdType"/>`
2、L10nData.xml
`<moqui.basic.LocalizedEntityField entityName="moqui.basic.Enumeration" fieldName="description" pkValue="PtidUSCCofChina" locale="zh_CN" localized="统一社会信用代码"/>`

then I began to execute command: ./gradlew load -Ptypes=seed,seed-initial,install
in database, the table Enumeration is no rows, and found it in LocalizedEntityField.

BUT! My logs is all successful:
 --- 2019-08-18 09:25:25.163 [   RequireNewTx] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed query with SQL [SELECT ENUM_ID, ENUM_TYPE_ID, PARENT_ENUM_ID, ENUM_CODE, SEQUENCE_NUM, DESCRIPTION, OPTION_VALUE, OPTION_INDICATOR, RELATED_ENUM_ID, LAST_UPDATED_STAMP FROM ENUMERATION WHERE ENUM_ID=?] and parameters [[enumId:PtidUSCCofChina]] in [0] seconds
--- 2019-08-18 09:25:25.163 [   RequireNewTx] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 making crud PreparedStatement for SQL: INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION, LAST_UPDATED_STAMP) VALUES (?, ?, ?, ?)
--- 2019-08-18 09:25:25.163 [   RequireNewTx] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 Executed update with SQL [INSERT INTO ENUMERATION (ENUM_ID, ENUM_TYPE_ID, DESCRIPTION, LAST_UPDATED_STAMP) VALUES (?, ?, ?, ?)] and parameters [[]] in [0] seconds changing [1] rows
--- 2019-08-18 09:25:25.163 [   RequireNewTx] DEBUG           org.moqui.impl.entity.EntityQueryBuilder []
 making crud PreparedStatement for SQL: SELECT ENUM_ID, ENUM_TYPE_ID, PARENT_ENUM_ID, ENUM_CODE, SEQUENCE_NUM, DESCRIPTION, OPTION_VALUE, OPTION_INDICATOR, RELATED_ENUM_ID, LAST_UPDATED_STAMP FROM ENUMERATION WHERE ENUM_ID=?

**Comment by jonesde** [comment]
There isn't enough information here to answer, but as a guess maybe you are looking at a different database than what you loaded data into or have cleared the database between runs.

The framework logs information about the database being used on startup, and for data loads it logs the files and records counts of data loaded. That's where I would recommend starting when looking into something like this.

**Comment by liaosf** [comment]
I'm so sorry, I found the reason today. I use the DbVisualizer to query all data in table, and filter my own  defined enumeration data in the Recordset. I'm set 1000 record per page, but my own data in the second page, so it look not exist.
