### ISSUE TITLE
Type conversion error in ObjectUtilities

### ISSUE THREAD

**Issue by WillWei1983** [moqui/moqui-framework#377]
In ObjectUtilities.basicConvert, there is a small issue. For example
javatype is java.sql.Timestamp,then theClass is java.sql.Timestamp. for the value like 1522028502000, then the origClass = value.getClass()  will be java.lang.Long.
then it will go to the return DefaultGroovyMethods.asType(value, theClass); which throw out the error in console and log.
it can be added a checking in line 89 in ObjectUtilities like this or just return the value for the developer to handle 
else if(theClass == java.sql.Timestamp.class && origClass == java.lang.Long){
     return new Timestamp(value)
}

**Comment by jonesde** [comment]
Just as the Groovy automatic type conversion isn't meant to cover every possible object pair (as seen from the error you got) the Moqui type conversion is also not meant to be universal. It's not a bug, just means you have to do type conversion in advance in some cases (or you're doing type conversion that isn't really 'correct').

That said, this is a reasonable conversion (Long to Timestamp) to support so feel free to submit a pull request if you'd like it to be there for convenience (ie so you don't have to do type conversion in advance or change the type conversion you're already doing).
