### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by guanhai562** [moqui/moqui-framework#393]
Our company has used your Moqui. There is no tutorial on the Internet. There is only one Chinese translation book in 2015. It's really too difficult for me

**Comment by aabiabdallah** [comment]
While the book contains plenty of information that is still valid today it is consider as obsolete. The source of up-to-date information is the [Documentation](https://www.moqui.org/docs) section on the Moqui website.

For the tutorial, you can start here:
[https://www.moqui.org/m/docs/framework/Quick+Tutorial](https://www.moqui.org/m/docs/framework/Quick+Tutorial)

**Comment by lightning-pro** [comment]
The company I am working in now using Moqui as our main business operation system development framework.
I am not sure if we are in the same company, I have writen a lot of demo for different business scenario for teammates to easy reference.
Maybe I will write some blogs in Chinese after the Chinese New Year, but mayb not........don't expected to much ^_^

> Our company has used your Moqui. There is no tutorial on the Internet. There is only one Chinese translation book in 2015. It's really too difficult for me

**Comment by guanhai562** [comment]
> While the book contains plenty of information that is still valid today it is considered obsolete. The source of up-to-date information is the [Documentation](https://www.moqui.org/docs) section on the Moqui website.
> 
> For the tutorial, you can start here:
> https://www.moqui.org/m/docs/framework/Quick+Tutorial

Oh, thank you very much. Your reply is instructive to me. I'll study hard for the tutorial!!
Although my English is not very good

**Comment by guanhai562** [comment]
> The company I am working in now using Moqui as our main business operation system development framework.
> I am not sure if we are in the same company, I have writen a lot of demo for different business scenario for teammates to easy reference.
> Maybe I will write some blogs in Chinese after the Chinese New Year, but mayb not........don't expected to much ^_^
> 
> > Our company has used your Moqui. There is no tutorial on the Internet. There is only one Chinese translation book in 2015. It's really too difficult for me

I think not. I work in Shenzhen. Can I find your tutorial blog online? The only blogs I see online are around 2016. Thank you first

**Comment by aabiabdallah** [comment]
I'm glad this helps. Can this issue be closed?

**Comment by jonesde** [comment]
It's great to see answers but I don't see any follow up on this so closing.

For the original poster: please use the moqui@googlegroups.com mailing list for questions rather than GitHub issues. See:

https://www.moqui.org/m/docs/moqui/Community+Guide
