### ISSUE TITLE
Error  :framework:compileGroovy FAILED

### ISSUE THREAD

**Issue by vrdwa** [moqui/moqui-framework#40]
Hi, 
I'm quite new to Moqui : have only been playing around with for a couple of weeks now. 
Anyhow, yesterday when I updated the code repository on my machine, i started getting the following error when i tried to run the code on my machine. ..[ it used to work well before the update yesterday] 
 
 /*****************************************************************************************************/
D:\testbed\GitHub\moqui-framework\framework\build\tmp\compileGroovy\groovy-java-stubs\org\moqui\impl\context\ExecutionContextImpl.java:11: error: ExecutionContextImpl is not abstract and does not override abstract method getContextBinding() in ExecutionContext
@groovy.transform.CompileStatic() public class ExecutionContextImpl
                                         ^
D:\testbed\GitHub\moqui-framework\framework\build\tmp\compileGroovy\groovy-java-stubs\org\moqui\impl\context\ExecutionContextImpl.java:43: error: getContextBinding() in ExecutionContextImpl cannot implement getContextBinding() in ExecutionContext
public  org.moqui.impl.context.ContextBinding getContextBinding() { return (org.moqui.impl.context.ContextBinding)null;}
                                              ^
  return type org.moqui.impl.context.ContextBinding is not compatible with org.moqui.context.ContextBinding
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
startup failed:
Compilation failed; see the compiler error output for details.

1 error

:framework:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':framework:compileGroovy'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 29.523 secs
 /*****************************************************************************************************/

Any advice on what i could be doing wrong or what i can do to share more details on the issue. 

Rgds
Sanjeev

**Comment by jonesde** [comment]
The ContextBinding class recently moved and from the error it looks like you have the old file in place still. If you pulled using git do a git status and make sure your local repo is clean, or just do a fresh clone or download.
