### ISSUE TITLE
added elasticsearch for windows break the command: ./gradlew downloadElasticSearchLinux

### ISSUE THREAD

**Issue by hansbak** [moqui/moqui-framework#406]
since last commit the command ./gradlew downloadElasticSearchLinux gives:

hans@hans-laptop:~/Desktop/servers/moquiContribute/moquiSystem$ ./gradlew downloadElasticSearchLinux

FAILURE: Build failed with an exception.

* What went wrong:
Task 'downloadElasticSearchLinux' not found in root project 'moquiSystem'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED

**Comment by jonesde** [comment]
Here's the diff from the commit to support Windows:

https://github.com/moqui/moqui-framework/commit/3132829cd68ab43c65b2719a33b3cc444aae70f9

The downloadElasticSearchLinux task has been replaced by downloadElasticSearch. The docs now need to be updated, but that should work fine (just leave off the 'Linux' at the end) or use the 'downloadel' shortcut (gradle will accept partial and ignore case if it matches a single task).

**Comment by jonesde** [comment]
The Run and Deploy document is now updated, the 3 references to downloadElasticSearchLinux changed to downloadElasticSearch and small text changes to mention Linux/Mac/Windows.

**Comment by hansbak** [comment]
Thanks, David.
