### ISSUE TITLE
reset password not work anymore

### ISSUE THREAD

**Issue by growerp** [moqui/moqui-framework#414]
standard system created with:
git clone https://github.com/moqui/moqui-framework.git moqui
cd moqui
./gradlew getComponent -Pcomponent=PopCommerce
./gradlew load
java -jar moqui.war

In the browser:
localhost:8080
click  'reset password' --> enter: 'john.doe' , look in the log for generated password.
login with 'john.doe' and generated password:, message: Password incorrect for username john.doe

**Comment by hansbak** [comment]
I looked further in the problem in MoquiShiroRealm.groovy where around line 248 the password is checked however not checked if the reset password is present in userAccount.
Looks like it is not within my knowledge of the system why this check is missing there....

**Comment by aabiabdallah** [comment]
The reset password can only be used to change the existing password and not for login. So, the correct flow is to reset the password then use the newly generated password to change the existing password and login.

**Comment by growerp** [comment]
Thanks for your explanation of the current implementation.
I expected the following behavior that when the reset password was used on the login screen, the system would prompt you for a new password...
