### ISSUE TITLE
Send JSON error in ScreenRenderImpl.getMenuData()

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/moqui-framework#419]
I think we should send JSON error in ScreenRenderImpl.getMenuData() if the screen not found for a path.

For example, 

       if (!fullUrlInfo.targetExists) { ec.web.sendError(404, "Screen not found for path ${pathNameList}", null); return null }

should be changed

        if (!fullUrlInfo.targetExists) { ec.web.sendJsonError(404, "Screen not found for path ${pathNameList}"); return null }

So that the error message and be handled by moqui.handleAjaxError properly

**Comment by jonesde** [comment]
This is a good idea, and cleaner on the client side for error handling (which I tested after these changes in vapps and the new qapps). The changes are in commit 4c83a42d.
