### ISSUE TITLE
StackOverflowError when a pre-validate seca rule call a service with a "parameters" in-param

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#42]
Parameters contains key of 'context', context contains 'parameters' key,  countArtifactHit method concat parameters and throw StackOverflowError

**Comment by jonesde** [comment]
In other words you declared an in-parameter called 'parameters' and it is a Map with an entry that has a key of 'context' and the value is the ec.context Map (or ContextStack rather)?

Yeah, don't do that. Certain names are not valid, or are reserved words, for service parameters including 'parameters', 'results', and 'context'. The Service Facade adds these to the context on its own to make them available to a service, and does special handling with them.

**Comment by chunlinyao** [comment]
Yes, you are right. The context is in parameters because when a transition calling service, it pass the whole context as in-map (needless keys will be removed after `convertValidateCleanParameters`). Service engine add 'parameters' into context before call a seca rule, because some seca rule will modify the parameters of service. It is straightforward to define a in-parameter as 'parameters'. Even I change the parameter name declared in in-parameter to others, and use a `<set field="others" from="parameters"/>` in actions of seca rule. The problem will not resolve. Because it's nothing about parameter name, It is really a parameter (Map) has indirect reference to itself. I think the bug is caused by `context` become a real key recently.

**Comment by chunlinyao** [comment]
A workaround like move parameters modification logic into actions of seca rule seems work.

**Comment by jonesde** [comment]
Do you have an easy way to reproduce this? Some code snippets would be helpful (like the SECA rule you are using).

Also, what do you mean by "move parameters modification logic into actions of seca rule"?

**Comment by chunlinyao** [comment]
I will try to create a minimal test code for it.  "move parameters modification logic into actions of seca rule” means write the parameters modification logic in <actions> tag of seca file (<actions><service-call …/><set field=“parameters.foo” from=“bar” /></action>), that not require to pass the parameters as a in-parameter into the service be called by seca rule.

**Comment by chunlinyao** [comment]
This is the test file https://gist.github.com/chunlinyao/cb71bc98ae7da8f9e4c294368f509ac6

Can reproduce before e7f5234e3bef24978b7eea99e0f712fa47304dfe

**Comment by chunlinyao** [comment]
After e7f5234 this can not be reproduced, I think it's ok to close it.
