### ISSUE TITLE
Gradle Tests

### ISSUE THREAD

**Issue by DavidMarkMadison** [moqui/moqui-framework#433]
I cannot get any of the Gradle/Groovy tests to succeed. I receive errors at the user level, and that User "john.doe" does not exist. I have attached an error snipet. I have tried this on a variety of branches, and am wondering if there is something extremely simple that I am missing, or is missing from the initial setup instructions.

[test.txt](https://github.com/moqui/moqui-framework/files/5137455/test.txt)

**Comment by jonesde** [comment]
The specific commands you ran would be helpful. From the log it looks like you didn't load data.

**Comment by DavidMarkMadison** [comment]
Closing issue. I must not have run load. I was certain that I did. Thanks!
