### ISSUE TITLE
CSV export have two extra blank rows before header.

### ISSUE THREAD

**Issue by chunlinyao** [moqui/moqui-framework#442]
Export CSV file from FindExample screen.
Version 3.0.0-rc6 added two extra blank rows before header.
The demo site 3.0.0-rc4 does not  has this problem.

It seems all text template output have extra blank lines. This image compares 3.0.0-rc6 with 3.0.0-rc4.
![blanklines](https://user-images.githubusercontent.com/148663/95679265-309e1100-0c04-11eb-87d3-d5df4af23e3a.png)

**Comment by jonesde** [comment]
It looks like FTL includes empty lines before the first #macro in the output, including the empty lines before and after the new #include that was added to various render modes to start reducing redundancy in them.

This is resolved for CSV output in moqui-runtime commit 4670764 (the default XML Screen/Form output macros are in the moqui-runtime repo). There is a similar change for the other render modes in moqui-runtime commit be901c7.
