### ISSUE TITLE
No way to call response.setHeader, instead of addHeader

### ISSUE THREAD

**Issue by eigood** [moqui/moqui-framework#447]
I have integrated keycloak into moqui(more discussion will happen later).  Its KeycloakOIDCFilter sets 'Access-Control-Allow-Credentials: true' in the response.  However, moqui then *also* calls addHeader(), on the same values.  When this happens, google-chrome denies the request, because it sees the duplicate, multi-valued header as 'true, true', and that breaks the invariant it is trying to ensure(namely, it just wants a single header).

I will send a MR for this shortly.

**Comment by jonesde** [comment]
See notes on: https://github.com/moqui/moqui-framework/pull/448

**Comment by jonesde** [comment]
This should be fixed with the changes for #448: https://github.com/moqui/moqui-framework/pull/448
