### ISSUE TITLE
How to implement Hotel room reservations?

### ISSUE THREAD

**Issue by hansbak** [moqui/moqui-framework#473]
I studied the moqui system and could not find asset reservation for rental of hotel rooms or equipment

My proposal:
Use a product: 'Standard room' and  Assets 'room 1', 'room2', 'room3' related to the product 'Standard room"
Use the requiredByDate in orderItem as the rental start date and the quantity for the number of days

then in AssetServices , services reserve#AssetForOrderItem add the function to check the assetReservation entity by adding a rentalFromDate and rentalThruDate field and use the quantity for the rental duration.

Use the rental reservation process for the productType: 'PtAssetUse

does this make sense?

Regards,
Hans

**Comment by jonesde** [comment]
Without more details I couldn't comment on a model that would meet business requirements, or even handle critical data elements based on business requirements. To throw out something general as a basis for this conversation:

- a hotel property may have one or more rooms
- a room may be reserved by a single party on a nightly basis for a period defined by a start and end date

For modeling the first step is to identify the best match for hotel properties and rooms, and IMO that is the Facility entity which has fields specific to physical locations like buildings and rooms within buildings. If the system were used to track asset depreciation then you may have an Asset record for the building, but it may not make sense to have an Asset record per room (unless the organization depreciates rooms independently).

For reservations the AssetReservation entity is not a good match, it is not designed for this and if an abstract model were created for hotel room (Facility) reservations it would not have much in common with AssetReservation. While a new entity could be used, the WorkEffort entity is the closest OOTB.

If you use Facility for hotel, child Facility for hotel room, and WorkEffort for facility scheduling there is already some support for this, including a calendar view for facilities.

**Comment by jonesde** [comment]
On a side note, the mailing list might be a better place to discuss this, though a better place is coming along and should be available soon (for a preview, not yet completely ready, see forum.moqui.org - this is an initiative from a volunteer, Michael Jones, who is spearheading the effort).

**Comment by hansbak** [comment]
Thanks for your answer, David,

However what would be your answer if i also want  to use this same process to rent equipment and tools?

have two different processes depending on the object to rent or would there be a way to combine it?

Regards,
Hans

**Comment by jonesde** [comment]
Yes, that would be the idea with equipment (use Asset records). In the ProductDefinitionEntities.xml file there is seed data for product types and two of them are Asset Use and Facility Use (there for future use, ie full flow not implemented for those; there may be some data model changes when that is done, ie full initial design not in place either).

On a side note Assets can be scheduled as well, and there is a Calendar tab for Asset like there is for Facility.

**Comment by hansbak** [comment]
I implemented to asset rental the following way:

added an Entity:
 ```
  <entity entity-name="AssetRental" package="growerp.product" cache="never">
        <field name="assetRentalId" type="id" is-pk="true"/>
        <field name="assetId" type="id"/>
        <field name="productId" type="id"/>
        <field name="orderId" type="id"/>
        <field name="orderItemSeqId" type="id"/>
        <field name="rentalFromDate" type="date-time"/>
        <field name="rentalThruDate" type="date-time"/>
        <relationship type="one" related="mantle.product.asset.Asset" short-alias="asset"/>
        <relationship type="one" related="mantle.product.Product" short-alias="product"/>
        <relationship type="one-nofk" related="mantle.order.OrderHeader" short-alias="orderHeader"/>
        <relationship type="one" related="mantle.order.OrderItem" short-alias="orderItem"/>
    </entity>

and a view with a product:
<view-entity entity-name="ProductAndAssetRental" package="growerp.product">
    <member-entity entity-alias="PROD" entity-name="mantle.product.Product"/>
    <member-entity entity-alias="RENTAL" entity-name="growerp.product.AssetRental"
        join-from-alias="PROD"><key-map field-name="productId"/></member-entity>
    <alias-all entity-alias="PROD"/>
    <alias-all entity-alias="RENTAL"/>
</view-entity>
   
```
and a service to search this entity to find a free asset for a certain time period:
```
   <service verb="get" noun="AssetsAvailableForProduct">
        <in-parameters>
            <parameter name="productId" required="true"/>
            <parameter name="fromDate" type="Timestamp" required="true"/>
            <parameter name="thruDate" type="Timestamp" required="true"/>
        </in-parameters>
        <out-parameters>
            <parameter name="availableAssetIds" type="List"/>
        </out-parameters>
        <actions>
            <service-call out-map="context"
                name="growerp.100.GeneralServices100.get#RelatedCompanyAndOwner"/>
            <entity-find entity-name="mantle.product.asset.Asset" list="assets">
                <econdition field-name="ownerPartyId" from="ownerPartyId"/>
                <econdition field-name="productId" from="productId"/>
            </entity-find>
            <set field="availableAssetIds" from="[]"/>
            <iterate list="assets" entry="asset">
                <entity-find-count entity-name="growerp.product.ProductAndAssetRental"
                     count-field="nbrUsed" cache="false">
                     <econdition field-name="productId" from="productId"/>
                     <econdition field-name="assetId" from="asset.assetId"/>
                     <econdition field-name="ownerPartyId" from="ownerPartyId"/>
                    <econditions combine="or">
                        <econditions combine="and"><!--order fromdate within -->
                            <econdition field-name="rentalFromDate"
                                operator="less-equals" from="fromDate"/>
                            <econdition field-name="rentalThruDate"
                                operator="greater-equals" from="fromDate"/>
                        </econditions>
                        <econditions combine="and"><!-- order thruDate within -->
                            <econdition field-name="rentalFromDate"
                                operator="less-equals" from="thruDate"/>
                            <econdition field-name="rentalThruDate"
                                operator="greater-equals" from="thruDate"/>
                        </econditions>
                        <econditions combine="and"><!-- both outside -->
                            <econdition field-name="rentalFromDate"
                                operator="greater-equals" from="fromDate"/>
                            <econdition field-name="rentalThruDate"
                                operator="less-equals" from="thruDate"/>
                        </econditions>
                    </econditions>
                </entity-find-count>
                <if condition="nbrUsed == 0">
                    <script>availableAssetIds.add(asset.assetId)</script>
                </if>
            </iterate>
        </actions>
    </service>    

```

Since i run multiple companies on the same system,  i always need to know the owner of the data.
Not sure how to contribute it?
regards,
Hans

**Comment by jonesde** [comment]
Hi Hans,

That's not how I would do it but if it meets your needs then it may be great for you.

I'm not sure what you mean by how to contribute it... what is it that you want to contribute and who do you want to contribute it to? You're always free to share your code and config, just as you did here or even in a public repo on GitHub or somewhere. If you are asking how you would go about getting this into the GitHub.com/moqui repositories, then you'd go through the normal process and submit one or more pull requests for review and moderation.

As a moderator for mantle-udm and mantle-usl I can tell you in advance that I would not merge these changes because I don't think it is a good long term design and it uses a new entity where WorkEffort could be used, leveraging the existing functionality around WorkEffort.

**Comment by hansbak** [comment]
Thanks for your comment however tools rental and hotel room rental is very much the same so i use the same for both.
Anyway, this implementation is in the GrowERP Moqui backend at https://github.com/growerp/growerp-moqui in the file: https://github.com/growerp/growerp-moqui/blob/master/service/growerp/100/OrderServices100.xml

The flutter frontend is at https://github.com/growerp/growerp with a demo at https://admin.growerp.org
