### ISSUE TITLE
Cannot mount http location as a subscreen 

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/moqui-framework#483]
I am trying to mount a http location as a sbuscreen like below but it dose not work.

`<subscreens-item name="AAA" menu-title="AAA" location="http://localhost:8080/qapps/marble/Order/FindOrder?orderType=Sales" menu-index="1"/>`

**Comment by jonesde** [comment]
The location value is invalid. Search around for subscreens-item to see examples. Most locations start with component:// (though they can be accessed in other ways too), and must point to the location of the Screen XML file.

**Comment by zhangwei1979** [comment]
In xml-screen-2.1.xsd, it says Subscreen location can include various prefixes to support including from a file, http, component, or a content repository. 
I would like to mount a screen with a parameter.
