### ISSUE TITLE
Cant find dependency org.codehaus.btm:btm:3.0.0-SNAPSHOT in Maven

### ISSUE THREAD

**Issue by zimskyhub** [moqui/moqui-framework#528]
JTA transition Manager Dependency org.codehaus.btm:btm:3.0.0-SNAPSHOT is Not Found in Maven Repository

**Comment by jonesde** [comment]
That jar file (btm-3.0.0-SNAPSHOT.jar) comes from the framework/lib directory based on a build from the btm repository on GitHub (actually a stabilization fork under my account: jonesde/btm on GitHub). It is not available in the maven central repository.

**Comment by zimskyhub** [comment]
got it, thanks, the btm-3.0.0-SNAPSHOT has not updated for many years, Is it will be Deprecated?
