### ISSUE TITLE
Add a new piece of data

### ISSUE THREAD

**Issue by eagle-china** [moqui/moqui-framework#530]
When I create relevant processes according to the demo (I have connected MySQL), when I add a piece of data, the text box of the new panel cannot be filled in，like that，The text box is gray and cannot be filled in.Didn't tutorial's groovy compile?
.
![Uploading image.png…]()

**Comment by jonesde** [comment]
This is likely because you are missing authorization data. Closing issue to clean things up, but feel free to reopen (or better, ask a question on forum.moqui.org; this may be intentional behavior, disabling forms when the user has read only authorization).
