### ISSUE TITLE
Question: Form-List Pagination (in container) not supported

### ISSUE THREAD

**Issue by mrovnanik** [moqui/moqui-framework#57]
This is not an issue, just a question. The pagination is not supported on form-list, if that form-list is inside a container. I found this feature in the long-term to do list, so I suppose it is not supported. Do I have that right?

An example - a form-list in container on the dashboard (PopCommerce), line 82.
https://github.com/moqui/PopCommerce/blob/master/screen/PopCommerceAdmin/dashboard.xml

**Comment by jonesde** [comment]
StackOverflow is generally a better place for questions, but in general please note that questions need to be detailed and specific or it is impossible to answer well.

Pagination is absolutely supported for form-list, and has been for a very long time. Where do you see this on a long-term to do list?

For the pagination controls to show you need to have pagination fields in the context when the form-list renders. This can be done by using the entity-find.search-form-inputs element, or manually setting the various pagination fields. There are also convenience methods for settings pagination fields like StupidUtilities.paginateList(), and you can see an example of using that in the CacheList.xml screen in the tools component (including in the moqui/moqui-runtime repository).
