### ISSUE TITLE
add locale parameter to l10n.localize and resource.expand

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-framework#6]
I am implementing a system that interacts with users through messages. These messages should be localized to the recipient's Locale, but currently the l10n.localize method, and the resource.expand methods only support using the current user's locale, which in this case is the sender.
Is it acceptable to add new methods (maintaining the old ones with the same behaviour) in order to achieve this, or is there a better solution?

**Comment by jonesde** [comment]
That's a very good point... I haven't run into a need for that but may soon. I'll add some methods to L10nFacade (or rather refactor existing methods for one set to take a locale parameter and another to call them with the current user's).

**Comment by jonesde** [comment]
In commit #3ea7818 I added methods that accept Locale (and for format TimeZone too) for localize, formatCurrency, and format.
