### ISSUE TITLE
Error while update child WikiPage

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#61]
I got this issue when update a child WikiPage, i.e in Demo Wiki which has following hierachy:
- Demo Page 1
    -  Child Page 1
    -  Child Page 2

I accessed Child Page 2 using this url: `http://localhost:8080/apps/hm/wiki/DEMO/Child+Page+2`
Page is found & rendered correctly. However, when edit this child (just the content, don't touch the Parent nor Page Name), error message raised like this:

```
Error in update of [[moqui.resource.wiki.WikiPage: [restrictUpdate:null, createdByUserId:EX_JOHN_DOE, lastUpdatedStamp:2016-06-03 22:00:47.282, restrictView:null, wikiPageId:100053, parentWikiPageId:null, wikiSpaceId:DEMO, pagePath:Demo Page 1/Child Page 2]]]

Error in update for:UPDATE public.WIKI_PAGE SET PAGE_PATH=?, LAST_UPDATED_STAMP=? WHERE WIKI_PAGE_ID=?

ERROR: duplicate key value violates unique constraint "wikipage_spcpth"
Detail: Key (wiki_space_id, page_path)=(DEMO, Demo Page 1/Child Page 2) already exists.

```

If I accessed Child Page 2 using the url with full path: `http://localhost:8080/apps/hm/wiki/DEMO/Demo+Page+1/Child+Page+2`, the update works well.

After checking the related service in WikiServices, I find that in the problematic case, pagePath='Child Page 2', (expected as 'Demo Page 1/Child Page 2') that cause service to update the entity and the index as well.

**Comment by jonesde** [comment]
This is fixed in commit #a13676a

The get#WikiPageInfo service now returns a normalized (full) pagePath so that in update#WikiPage we don't think we are moving it.
