### ISSUE TITLE
Issues when using sendJsonResponse in service for rest call

### ISSUE THREAD

**Issue by lightning-pro** [moqui/moqui-framework#610]
I am using sendJsonResponse in service for a rest call like belows

<service verb="get" noun="AllEntitiesInfo">
        <in-parameters>
            <parameter name="orderByField" default-value="fullEntityName"/>
            <parameter name="filterRegexp"/>
            <parameter name="masterEntitiesOnly" type="Boolean"/>
            <parameter name="excludeViewEntities" type="Boolean"/>
        </in-parameters>
        <actions>
            <script>
                List result = ec.entity.getAllEntitiesInfo(orderByField, filterRegexp, masterEntitiesOnly, excludeViewEntities)
                ec.web.sendJsonResponse(result)
            </script>
        </actions>
    </service>

And for the rest call, handleServiceRestCall would call the sendJsonResponse again to send the response back to api caller.
normally the sendJsonResponse in handleServiceRestCall would be an empty response string like {}, and this empty {} normally won't be send back to api caller.
BUT sometimes(I think it is related to the number of the response data), handleServiceRestCall's sendJsonResponse  will send the {}  appending to the end of the response string in service ec.web.sendJsonResponse().
for my service above, when calling the api by setting the masterEntitiesOnly to true, api will send the right response back to api caller(about 130 rows in result).
but when calling it by setting the masterEntitiesOnly to false, there are about 850 rows in my system, and the response back to the api will be the 850 [] list data and an empty {} in the end after the []. this response is a bad json response string for caller.

**Comment by jonesde** [comment]
What are the steps to reproduce starting with stock moqui-framework? In order to research and fix issues this is the necessary first step.

**Comment by lightning-pro** [comment]
Here is the steps for reproduce the issue I mentioned
 1. Make sure clone the mantle related components to the project so that we will have lots of entities
 2. In the Example component, at the end of the ExampleServices.xml, add the below service
 `<service verb="get" noun="AllEntitiesInfo">
        <in-parameters>
            <parameter name="orderByField" default-value="fullEntityName"/>
            <parameter name="filterRegexp"/>
            <parameter name="masterEntitiesOnly" type="Boolean"/>
            <parameter name="excludeViewEntities" type="Boolean"/>
        </in-parameters>
        <actions>
            <script>
                List result = ec.entity.getAllEntitiesInfo(orderByField, filterRegexp, masterEntitiesOnly, excludeViewEntities)
                ec.web.sendJsonResponse(result)
            </script>
        </actions>
    </service>`

3. In the example.rest.xml, and the below resource to the end of file
`<resource name="entities" description="example for lots of data response in rest call">
        <method type="get">
            <service name="moqui.example.ExampleServices.get#AllEntitiesInfo"/>
        </method>
    </resource>`

4. open the http://localhost:8081/qapps/tools/dashboard(use your own port) and click the Example REST API(29) button to open the Swagger UI to test the api (http://localhost:8081/toolstatic/lib/swagger-ui/index.html?url=http://localhost:8081/rest/service.swagger/example#/entities/get_entities)

5. Select the masterEntitiesOnly with true value, and select the excludeViewEntities with false value; 
The request url will be http://localhost:8081/rest/s1/example/entities?masterEntitiesOnly=true&excludeViewEntities=false; and the Response body will be a good response as 
[
...
,
{
    "entityName": "SystemMessageRemote",
    "package": "moqui.service.message",
    "isView": "false",
    "fullEntityName": "moqui.service.message.SystemMessageRemote",
    "tableName": "SYSTEM_MESSAGE_REMOTE"
  }
]

6. Select the masterEntitiesOnly with false value, and select the excludeViewEntities with false value; 
The request url will be http://localhost:8081/rest/s1/example/entities?masterEntitiesOnly=false&excludeViewEntities=false
and the Response body will be a bad response as 
can't parse JSON.  Raw result:
[
...
,
 {
  "entityName" : "TestNoSqlEntity",
  "package" : "moqui.test",
  "isView" : "false",
  "fullEntityName" : "moqui.test.TestNoSqlEntity",
  "tableName" : "TEST_NO_SQL_ENTITY"
} ]{ }


As I debug the framework code ,I can see that the sendJsonResponse in WebFacadeImpl.groovy will be executed two times because of the service use ec.web.sendJsonResponse(result) to call it first and the  handleServiceRestCall in WebFacadeImpl.groovy will call it again after the RestApi.RestResult restResult = eci.serviceFacade.restApi.run(extraPathNameList, eci); 
and most of the time, the second call won't send the {} back to the client, 
but it happened when setting masterEntitiesOnly=false to have all the entities definition data response.

**Comment by lightning-pro** [comment]
Thank you for your explanation. and it make sense not to use ec.web in service.
BTW In the manle-usl ProjectServices.xml get#ProjectParties, there are ec.web.sendJsonResponse. as the response data is not big, it works fine
