### ISSUE TITLE
The size function of List in WikiServices.xml

### ISSUE THREAD

**Issue by newmann** [moqui/moqui-framework#643]
When use Java 17, the function size of List should have double bracket，otherwise errors raised。
for example， in  WikiServices.xml line 170，171：
`
                <if condition="!pagePath &amp;&amp; extraPathNameList.size > 1">
                    <iterate list="extraPathNameList[1..extraPathNameList.size-1]" entry="pathName">
`
should ：
`
                <if condition="!pagePath &amp;&amp; extraPathNameList.size()） > 1">
                    <iterate list="extraPathNameList[1..extraPathNameList.size() - 1]" entry="pathName">
`
there are no errors when use Java 11.

Does anyone know what the reason is?

**Comment by aabiabdallah** [comment]
This has to do with how Groovy treats properties. See: https://stackoverflow.com/questions/26532434/groovy-has-a-size-property-for-collection

**Comment by newmann** [comment]
Doesn't the source code need to be modified?
