### ISSUE TITLE
ec.user.context does not have content when after-login actions in web-app set ec.user.context

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#66]
I add service call of setup#UserOrganizationInfo in after-login actions in web-app element. The service setup#UserOrganizationInfo set ec.user.context.userOrgIds, filterOrgIds and activeOrgId. They have content immediately after service call in after login actions (the are logged). But they can't be access outside of after-login actions. I printed them in a screen, but ec.user.context is empty.

**Comment by shendepu** [comment]
I shall not use ec.user.context to share data, instead using ec.web.getSession().setAttribute to share data across requests for one session.

**Comment by jonesde** [comment]
The setup#UserOrganizationInfo was designed to run in screen.pre-actions, but could be used elsewhere. I added a description to the service that mentions this.

**Comment by shendepu** [comment]
The setup#UserOrganizationInfo is bound to login user. The result would be same if party relationship is not changed, then it make more sense to run once and all request can access userOrgIds, filterOrgIds and activeOrgId. 

I created pull request https://github.com/moqui/mantle-usl/pull/22 that also set them in session.

**Comment by jonesde** [comment]
Data may change in the course of a session, and in general the approach is to use the cache to speed it up rather than retaining data that isn't so easy to clear out when underlying data changes.

**Comment by shendepu** [comment]
Yes. using cache it better.
