### ISSUE TITLE
AuthenticationRequiredException while loading data for tenant

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#73]
While loading data for tenant using command line, for example: >`gradlew load -PtenantId=EXAMPLE1`
an `AuthenticationRequiredException `caused at a service call, i.e `org.moqui.impl.EntityServices.clone#DataDocument
`
I find that in Moqui.java, the code to change tenant [L87](https://github.com/moqui/moqui-framework/blob/master/framework/src/main/java/org/moqui/Moqui.java#L87) should be put before user login action.
It worked after change in accordingly.

**Comment by jonesde** [comment]
Thank you, I made that change in commit #949b815. Please confirm this fixes it for you.

**Comment by locnguyenx** [comment]
It fixed.
