### ISSUE TITLE
XML Schema Location is not correct in almost all xml files

### ISSUE THREAD

**Issue by visvendra** [moqui/moqui-framework#76]
Files ending with *-2.0.xsd, don't exist on given location. I checked for *-1.6.xsd files, those are available. What is the correct path for *-2.0.xsd files?

**Comment by jonesde** [comment]
Moqui Framework 2.0.0 is not yet released, and the *-2.0.xsd files will not be on the web site until it is. If you are using the latest from the master branch you should generally use local XSD files anyway.
