### ISSUE TITLE
Return escaped string via json reponse

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#79]
The REST api can save unicode characters correctly in database, but return escaped string to client.

So I simply test with ec.web.sendJsonResponse

    ec.web.sendJsonResponse([contentText: '测试'])

The return is 

    { "contentText": "\u6d4b\u8bd5" }

**Comment by chunlinyao** [comment]
It looks like a correct behavior.

**Comment by shendepu** [comment]
Why should it be correct behavior? Shouldn't it be

    { "contentText": "测试" }

And it was before.

**Comment by chunlinyao** [comment]
rfc4627 say `Any character may be escaped`, so escaped and unescaped format are all correct. At lease in Chrome `"\u6d4b\u8bd5" === "测试"` returns `true`.

**Comment by shendepu** [comment]
It is equal, but the actual problem is the 

    { "contentText": "\u6d4b\u8bd5" } 

can be JSON.parse to 

    {contentText: "测试"}

but if the text contains double quote like the map [contextText: '测试"'], the json response is 

    {"contentText":"\u6d4b\u8bd5\""}

Then this can't be JSON.parse directly, since the \ of \" is not escaped. so there are two solutions: 

client javascript replace \" in json response with \\", then it can be JSON.parse to correct json object.

    { "contentText": "\u6d4b\u8bd5\\"" } 

server, actually sendJsonReponse, escapes the json response, so the json response string is 

    {"contentText":"\\u6d4b\\u8bd5\\""}

Server side seems hard since String.replaceAll can't be used. Groovy JsonBuilder does not print correct json string if double quotes is in the content.

**Comment by jonesde** [comment]
@shendepu what would you propose for this? Moqui doesn't do anything related to this before passing the object (Map) to the Groovy JsonBuilder, so the only alternative would be to use a different library for getting JSON text for Java objects... well that or working upstream with the Apache Groovy team to improve this. 

I'm not opposed to using something else (as long as it's not a crazy huge jar, and I think there are a couple options even among the jars we're already using for other things). Have you tried any other libraries that you like?

**Comment by shendepu** [comment]
I run test from javascript to parse the json result returned by sendJsonResponse() that contains double quote and single quote, the json response in text is 

    {"name": "\u6211\u4eec\u4e00\u53ea\u9c7c\""}

and it can be JSON.parse if called fetch by javascript 
![image](https://cloud.githubusercontent.com/assets/4743845/17203625/24847e6e-54d3-11e6-8122-f50f30e04fea.png)

but it can't be parsed if copy the json text and run JSON.parse
![image](https://cloud.githubusercontent.com/assets/4743845/17203706/86809788-54d3-11e6-87b1-950881ef8a51.png)

I don't know exact reason of this. But it is not an issue for javascript client. So this issue can be closed.
