### ISSUE TITLE
Problem when navigating WikiPage by SpacePageTree

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#84]
Issue happen when access a WikiPage with blank in name (i.e "Demo Page 1") from the WikiSpace tree.

The url of this page in the tree link is: http://localhost:8080/apps/hm/wiki/DEMO/Demo+Page+1

As a result, HM wiki screen can't find that Page and open the screen to create new one with default name is "Demo+Page+1".

If I create a child page of "Demo Page 1", i.e "Child Page 1", then the new page name is "Child+Page+1" and parent "Demo+Page+1". After commit, the new child page will not exist to expected path due to wrong parent.

Maybe there's problem when encode the page name with blank into url. The blank space char should be encoded into "%20" instead of "+"

**Comment by jonesde** [comment]
This is fixed in commit #5672ce8.
