### ISSUE TITLE
Wiki - can't move page to other location if new Parent dir not created

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-framework#86]
Replicate scenario:
1. Existing page to be moved: <wikiroot>/OldParent/Page1.md
2. Create new page, i.e <wikiroot>/NewParent
3. Edit Page1, change Parent Path to: <wikiroot>/NewParent

Result: the service update#WikiPage complete sucessfully, and Moqui redirect to new URL .../NewParent/Page1. However, the Page1 is not moved to NewParent yet, then system display a blank new Create Page form.

Note: it worked well if at step 3, we created new page under NewParent, or we move an existing page to an existing Folder, not page.

**Comment by jonesde** [comment]
In my local tests this is fixed in commit #ab4ddc2 (just pushed). Would you try it and see if it works for you? If so this issue can be closed.

**Comment by locnguyenx** [comment]
It works as expected. Thanks.
