### ISSUE TITLE
MySql performance >10 times slower than H2 on Speed Test

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-framework#94]
I used the moqui-framework (c983718) with MySql database, it is simply use the default MySql datasource configuration, the performance on entity operation (without cache) is more than 10 times slower than H2 database. 

Below are snapshots of two environments (only change is the datasource configuration)
H2:
![speed-test-with-h2](https://cloud.githubusercontent.com/assets/4743845/17954404/6e94c9b0-6aad-11e6-917a-d2edd60eadcd.png)

MySql:
![speed-test-with-mysql](https://cloud.githubusercontent.com/assets/4743845/17954414/7cdcd31e-6aad-11e6-88eb-04909d1ce2e7.png)

this is run at my Macbook Pro with SSD. and it is similar (10 times difference) at server with HDD.

I recall it was not so bad with MySql datasource before.

**Comment by shendepu** [comment]
Quick profile with JProfiler
![image](https://cloud.githubusercontent.com/assets/4743845/17954907/c9cb378a-6ab0-11e6-8503-40ea66b4bb44.png)

most of time is spent on jdbc part (70%).  

comparing to h2 (20%)
![image](https://cloud.githubusercontent.com/assets/4743845/17954952/2ff6dda2-6ab1-11e6-9606-20622610a1e7.png)

Maybe it is mysql-connector issue? I tried mysql-connector-java version 5.1.27 and 5.1.38

**Comment by jonesde** [comment]
This is normal for an external database like MySQL compared to H2. H2 really is very fast, but only scales so well. Part of the reason H2 is fast is there is no network interface to go over when running embedded, and it is also really efficient in general.

The difference from past versions of Moqui is that the Entity Facade itself is much much faster, has been optimized a great deal. This means there is less overhead per DB query so the difference in database speed shows more.

Note that for individual transactions run serially there is a big performance difference, but try something like a multi-threaded load test running real screens and you'll see much less difference. In other words, with external database overhead there is more latency, but the throughput on loads with high numbers of users does just fine.
